"""Quiz banks for the curriculum lessons and case studies, keyed by catalogue ID.

The catalogue's knowledge checks are short-answer, so each bank rewrites
them as MCQ or multi-select questions with plausible wrong answers, then adds
questions on the worked example, practice task and failure modes. Every
answer is taken from the lesson text in docs/learning. sd-01's bank lives
with its hand-adapted notes in learn/curriculum.py.

Choices are listed right answer first; the quiz shuffles them. Keep every
choice in a question about the same length, tone and specificity, so the
right answer can't be spotted by being the longest or the only hedged one.
A yes/no question gets a wrong answer on each side. The rules are in
docs/learning/CONTENT_STANDARDS.md and learn/test_content_standards.py
checks them. The detail belongs in the explanation, not the right choice.
"""


def mcq(prompt, right, wrong, explanation):
    return {'prompt': prompt, 'choices': [(right, True)] + [(w, False) for w in wrong], 'explanation': explanation}


def multi(prompt, choices, explanation):
    return {'kind': 'multi', 'prompt': prompt, 'choices': choices, 'explanation': explanation}


BEGINNER = {
    'sd-02': [
        mcq('A client repeats DELETE /tasks/9. The first call returns 204 and the second returns 404. Is DELETE still idempotent?',
            'Yes. Idempotence is about the effect on server state, not matching status codes.',
            ['No. An idempotent request has to return the same status code on every repeat.',
             'No. Only safe methods such as GET can be idempotent under HTTP semantics.',
             'Yes, but only because 404 counts as a success code for a DELETE request.'],
            'After either call the task is gone. The second response differs, but repeating the request did not change state further.'),
        mcq('POST /exports returns 202 Accepted. What does that tell the caller?',
            'The export was accepted for processing; it may not have finished yet.',
            ['The export file has been generated and is ready to download now.',
             'The server created the export resource, the same promise as 201.',
             'The request failed validation and the caller should send it again.'],
            '202 means accepted, not completed. Completion needs a separate observation, such as an operation status URL '
            'backed by durable operation state.'),
        multi('Which statements about HTTP method semantics are correct? Select all that apply.',
              [('GET is safe: the client is not asking the server to change state.', True),
               ('PUT and DELETE are idempotent in their intended effect on state.', True),
               ('POST becomes idempotent whenever the request body is identical.', False),
               ('A safe method must return a byte-identical response every time.', False)],
              'Safety and idempotence describe what the client asks the server to change. POST has no general idempotency guarantee.'),
        mcq('Two clients read a task title at ETag v7. Client 1 writes with If-Match: v7 and creates v8. Client 2 then writes with If-Match: v7. What should happen?',
            'Reject client 2 with 412 Precondition Failed so it can refresh first.',
            ['Apply client 2\'s title, since the write that arrives last should win.',
             'Merge the two titles automatically and store the result as v9.',
             'Return 202 Accepted and queue client 2\'s write to apply later.'],
            'If-Match makes the write conditional on the version the client read. A stale precondition is detected instead of '
            'silently overwriting v8, and client 2 refreshes or resolves its edit.'),
        mcq('Why is it unsafe to retry POST /payments automatically?',
            'POST has no general idempotency guarantee, so a retry can charge twice.',
            ['HTTP forbids clients from resending a POST under any circumstances.',
             'A retried POST is always rejected with 412 Precondition Failed.',
             'After a timeout, the original POST response can never be read again.'],
            'Automatic retries of POST are unsafe unless the API defines deduplication, such as a stable request key.'),
    ],
    'sd-03': [
        mcq('A stable service handles 50 requests/s with a 0.2 s mean response time. Using Little\'s Law, how many requests are in flight on average?',
            '10', ['250', '0.004', '2.5'],
            'L = lambda × W = 50 × 0.2 = 10, provided throughput and latency are measured at the same boundary.'),
        multi('CPU sits at 20% but requests are timing out. What could explain it? Select all that apply.',
              [('Requests are waiting on locks held by other requests.', True),
               ('Requests are waiting for a free database connection.', True),
               ('Requests are queued behind slow network responses.', True),
               ('Low CPU proves the service has capacity for every request.', False)],
              'Requests can wait on locks, connections, network responses or queues without consuming CPU.'),
        mcq('Throughput stays at 200 requests/s while mean response time rises from 0.15 s to 0.6 s. What happens to average in-flight work?',
            'It rises to 120 requests.',
            ['It stays at 30 requests.', 'It falls to 7.5 requests.', 'It doubles to 60 requests.'],
            'In-flight work is throughput × time in system: 200 × 0.15 = 30 before, 200 × 0.6 = 120 after. The extra work can '
            'hold memory and sockets even while CPU stays low.'),
        mcq('990 requests take 20 ms and 10 take 2,000 ms. The mean is 39.8 ms. What does the mean hide?',
            'Ten severe delays that a tail percentile would reveal.',
            ['Nothing; the mean is the right summary of user experience.',
             'That overall throughput fell during the measurement.',
             'That the service silently dropped the slowest requests.'],
            'Tail percentiles describe slow requests. A mean can hide a small but painful slow population.'),
        mcq('Starting empty, a worker group receives 120 jobs/s and completes 100/s for five minutes. Arrivals then fall to 80/s. How long does the backlog take to drain?',
            'About 300 seconds.', ['About 75 seconds.', 'About 60 seconds.', 'It never fully drains.'],
            'The backlog grows by 20 × 300 = 6,000 jobs. Spare capacity is 100 − 80 = 20 jobs/s, so draining takes 300 s, assuming fixed capacity and no retries.'),
    ],
    'sd-04': [
        mcq('Does adding await make a CPU-heavy loop run in parallel?',
            'No. await only lets a task pause; the CPU work still runs one step at a time.',
            ['Yes. Each await statement hands the next loop iteration to another CPU core.',
             'Yes, as long as the loop runs inside an asyncio task group.',
             'No. await makes the loop slower because it moves to a background thread.'],
            'async syntax lets a task yield at awaitable operations. CPU parallelism needs an execution model that supports it.'),
        mcq('When is a process-local mutex insufficient to protect an inventory rule?',
            'When other processes or servers can change the inventory without it.',
            ['Only when the mutex is held for longer than about one second at a time.',
             'Never, because a mutex serializes every update to the data.',
             'Only when the database underneath has transactions disabled.'],
            'A process-local lock coordinates only that process. The shared authority has to enforce the rule.'),
        mcq('Two workers both read remaining_seats = 1, both see a seat, and both write 0 and issue a ticket. Which fix enforces the rule at the shared boundary?',
            'One transaction: decrement only if remaining_seats > 0, then create the reservation.',
            ['A lock held inside each web server process around the read and the write.',
             'Have both workers re-read remaining_seats until they agree on a value.',
             'Write remaining_seats twice so the second write can confirm that the first one landed.'],
            'Decrement only if a seat remains, check that exactly one row changed, and create the reservation in the same '
            'transaction. The database enforces the check and the change atomically.'),
        mcq('Two increments both read balance = 10 and both write 11. What happened?',
            'A lost update: two increments produced a single net increase.',
            ['Nothing went wrong: 11 is the correct final balance here.',
             'A deadlock, which the database then resolved correctly.',
             'The second write was rolled back automatically by the database.'],
            'Read-then-write interleavings lose updates. An atomic balance = balance + 1 lets the database serialize them.'),
        multi('Which statements about concurrency are correct? Select all that apply.',
              [('Concurrency means overlapping progress; parallelism means simultaneous work.', True),
               ('A blocking call inside an event loop can stop it serving other tasks.', True),
               ('Cancelling a coroutine proves its remote effects were rolled back.', False),
               ('Optimistic version checks never need a retry, even under conflict.', False)],
              'A cancelled coroutine may already have triggered an external effect. Optimistic checks work well when conflicts are rare but must retry when they occur.'),
    ],
    'sd-05': [
        mcq('Why might a sequential scan be the right plan?',
            'When the query needs much of the table, one pass beats many index lookups.',
            ['Sequential scans are faster than index scans for every kind of query.',
             'The planner scans sequentially only when the table has no usable index at all.',
             'When the index is newer than the statistics the planner is holding.'],
            'An index scan is not always better. Low-selectivity queries can favor reading the table sequentially.'),
        mcq('Is EXPLAIN ANALYZE a read-only inspection for any SQL statement?',
            'No. It really executes the statement, so writes and side effects happen.',
            ['Yes. It only reports the planner\'s estimated costs for the statement.',
             'Yes. PostgreSQL always rolls it back automatically when it finishes.',
             'No. It is read-only, but it takes an exclusive lock on every table.'],
            'EXPLAIN shows the planned strategy; EXPLAIN ANALYZE executes and measures. Use a disposable environment for statements with effects.'),
        mcq('A query filters tenant_id = 7 and status = \'open\', sorts by created_at and id descending, and returns 20 rows. Which index is the lesson\'s candidate?',
            '(tenant_id, status, created_at, id)',
            ['(created_at, id, tenant_id, status)', '(status, created_at, tenant_id)', '(id, tenant_id, status, created_at)'],
            'It groups the equality filters before the ordered range, with id breaking timestamp ties. Compare plans on representative data before trusting it.'),
        mcq('A dashboard loads 50 projects, then runs one query per project to fetch its owner. What is the main problem?',
            'An N+1 pattern: 51 queries where a join or one batched query would do.',
            ['A missing index on the projects table slowing the first query.',
             'A sequential scan on the owners table for each project lookup.',
             'The dashboard page is not cached, so it should be cached for a full day.'],
            'Fetch owners with a join or one bounded query keyed by owner IDs. An index may speed up each lookup while leaving the avoidable round trips in place.'),
        multi('What can an extra index cost? Select all that apply.',
              [('Extra work on every write that changes indexed columns.', True),
               ('More storage space for the index structure itself.', True),
               ('Ongoing maintenance, such as watching for bloat.', True),
               ('Slower reads for every query on the table, even unrelated ones.', False)],
              'Every extra index adds write, storage and maintenance costs. It does not slow down unrelated reads.'),
    ],
    'sd-06': [
        mcq('Is "one million registered users" enough for a capacity estimate?',
            'No. You also need activity, actions per user, timing, payloads and retention.',
            ['Yes. Divide one million by 86,400 to get the requests per second.',
             'Yes, once a 20% headroom margin is added on top of the registered user count.',
             'No. You need the number of servers first, then the user count.'],
            'Registered users say nothing about how often people act, how large requests are, or when they arrive.'),
        mcq('A flash crowd appears. Which assumption changes first?',
            'The peak arrival pattern and concurrency.',
            ['The total number of registered users.', 'How long the data has to be retained.',
             'The average size of each request payload.'],
            'The registered-user count may not change at all. Daily averages conceal bursts, so estimate steady and peak demand separately.'),
        mcq('100,000 daily active learners each load 20 lessons a day. What is the average read rate?',
            'About 23 reads/s.', ['About 2,000 reads/s.', 'About 231 reads/s.', 'About 0.23 reads/s.'],
            '2 million reads a day ÷ 86,400 s ≈ 23.15 reads/s. A 20× peak would be about 463 reads/s.'),
        mcq('Which of these is an invariant rather than a performance objective?',
            'Never confirm two owners for one seat.',
            ['99% of accepted reads finish within 300 ms.',
             '99.9% of requests succeed over 30 days.',
             'p95 search latency stays under 250 ms.'],
            'An invariant must always hold. An objective states a target over a measurement window.'),
        mcq('100,000 users each submit five 500-byte events a day, kept for 365 days. How much raw event storage is that?',
            '91.25 GB', ['7.5 GB', '250 MB', '912.5 GB'],
            '250 MB a day × 365 = 91.25 GB in decimal units, before indexes, replicas and backups.'),
        mcq('Before choosing the number of application servers, what should you measure?',
            'What one server sustains at the latency and error targets, plus its downstream load.',
            ['The number of registered users the product expects in its first year.',
             'The requests per second the vendor advertises for each of its server sizes and tiers.',
             'The average daily traffic, since the peaks cancel out over a full day.'],
            'Measure throughput at the required objectives and the database and cache demand of a realistic request mix. '
            'Include failure headroom rather than dividing by an untested requests-per-server guess.'),
    ],
}

INTERMEDIATE = {
    'sd-07': [
        mcq('Should a database slowdown always fail application liveness?',
            'No. Restarting healthy app processes can deepen a database incident.',
            ['Yes. Liveness should mirror the health of every dependency it uses.',
             'Yes, so that the load balancer stops sending the pod any traffic.',
             'No. Liveness probes cannot call a database, so it is not possible.'],
            'A liveness probe that fails whenever the database is slow can restart every application server during a database incident.'),
        mcq('Does an equal connection count across instances mean equal request load?',
            'No. Connections differ in how many requests they carry and what each costs.',
            ['Yes. Each connection carries exactly one request during its entire lifetime.',
             'Yes, whenever the balancer uses a round-robin routing policy.',
             'No. Equal counts mean equal load only for TLS-encrypted traffic.'],
            'A long-lived connection carrying many requests makes connection counts a poor proxy for load.'),
        mcq('Four instances each sustain 100 requests/s at the target latency, and traffic is 240/s. Two instances fail. What happens?',
            'The two survivors each see 120/s, above their measured limit.',
            ['Each survivor sees 60/s, which is well within its limit.',
             'Each survivor sees 80/s, just under its measured limit.',
             'Total traffic falls to 120/s as clients give up and leave.'],
            'With one instance gone each sees 80/s; with two gone, 120/s. The arithmetic assumes balanced requests of similar cost.'),
        multi('Which statements about Kubernetes probes are correct? Select all that apply.',
              [('Readiness decides whether a pod receives Service traffic.', True),
               ('A failing liveness probe can trigger a container restart.', True),
               ('A startup probe holds off other checks during slow startup.', True),
               ('A failing readiness probe deletes the pod and schedules another.', False)],
              'Readiness withdraws a pod from traffic; liveness restarts containers; startup probes protect slow starts.'),
        mcq('An instance is being shut down. What should happen first?',
            'Withdraw readiness and keep serving while routing catches up.',
            ['Kill the process right away and let the clients retry elsewhere.',
             'Close every open connection immediately to free up resources.',
             'Fail the liveness probe so that the orchestrator restarts the pod.'],
            'Then stop admitting new work, let short requests drain within a bounded grace period, and force termination only at the declared deadline.'),
    ],
    'sd-08': [
        mcq('Does a 30-second TTL alone guarantee that every served value is at most 30 seconds behind the authority?',
            'No. Delayed fills and stale upstream reads can make data older than its TTL.',
            ['Yes. The TTL bounds how stale any served value can be, exactly.',
             'Yes, as long as the cache holds its entries only in memory and never on disk.',
             'No. A TTL only limits memory use; it has no effect on freshness.'],
            'TTL limits a copy\'s lifetime. It is not a complete consistency protocol.'),
        mcq('What does HTTP Cache-Control: no-cache mean?',
            'A stored response must be revalidated before it is reused.',
            ['Caches must never store the response in the first place.',
             'The stored response expires after zero seconds and is deleted.',
             'Only a CDN may store the response; browsers must not keep it.'],
            'no-cache allows storage but requires validation before reuse; no-store forbids storage by caches subject to the directive.'),
        mcq('At 1,000 reads/s and a 95% hit rate, the origin serves about 50 reads/s. A restart empties the cache. What happens?',
            'Origin demand can climb toward 1,000 reads/s until it refills.',
            ['Origin demand stays near 50 reads/s while the cache warms up.',
             'Origin demand drops to zero because the cache is unavailable.',
             'Origin demand rises to 1,050 reads/s: misses plus the refills.'],
            'A cache outage needs a controlled fallback; sending every miss to an already saturated database is not a recovery plan.'),
        mcq('Reader A misses and reads version 4. Writer B commits version 5 and invalidates the key. Reader A then fills the cache with version 4. What went wrong?',
            'A stale-fill race: A\'s fill landed after B\'s invalidation.',
            ['The TTL was too short, so version 5 expired before reads came.',
             'The eviction policy removed version 5 under memory pressure.',
             'Nothing; invalidating a key guarantees the next read is fresh.'],
            'Invalidation happened, yet stale data returned. Version-aware fills or a coherence protocol stop an older version replacing a newer one.'),
        mcq('A product page may show stock up to 30 seconds old, but checkout must never sell unavailable stock. Where should the checkout decision be made?',
            'At the authoritative store, with a conditional update.',
            ['From the cached stock count, which is at most 30 s old.',
             'From the CDN copy of the product page the buyer loaded.',
             'In the browser, using stock from the last page load.'],
            'Cache the display with an explicit freshness policy, and enforce the inventory invariant where the data is authoritative.'),
        multi('What belongs in a shared cache key for a multi-tenant API? Select all that apply.',
              [('The tenant the answer belongs to.', True),
               ('The authorization-relevant scope.', True),
               ('Representation variants, where used.', True),
               ('The exact time the request arrived.', False)],
              'Never let a shared cached answer bypass an access check.'),
    ],
    'sd-09': [
        mcq('A request fails with a pool acquisition timeout. Does that prove the database query ran slowly?',
            'No. The request may never have obtained a connection at all.',
            ['Yes. The pool timeout measures how long the query ran.',
             'Yes, because pools only time out while a query is running.',
             'No. It proves the database server rejected the login.'],
            'Waiting for a connection and executing a query are different stages.'),
        mcq('Why include deployment overlap in a connection budget?',
            'Old and new instances run together, adding their pools up.',
            ['Deployments reset every pool to zero connections at once.',
             'Databases double their connection limit during a deploy.',
             'Rollouts close idle connections, so the pools refill twice.'],
            'If a deployment temporarily doubles instances, potential demand can double with it before the old fleet drains.'),
        mcq('12 application instances each run 2 worker processes with a pool of 10. What is the maximum connection budget?',
            '240', ['120', '24', '480'],
            '12 × 2 × 10 = 240, which already exceeds a database allowing 200 connections, before background jobs or rollout overlap.'),
        mcq('Latency rose from 80 ms to 800 ms. Queries still take about 50 ms, but pool acquisition takes 700 ms. Why might doubling the pool size fail?',
            'With no spare database capacity, the queue just moves into the database.',
            ['Pool size cannot be changed while the application is running.',
             'A larger pool would cut each query\'s execution time from 50 ms to about 5 ms.',
             'It would fail because pools must be sized as powers of two.'],
            'More connections add contention if the database is saturated. Check transaction durations and leaks, aggregate '
            'connection budgets, and database saturation or lock waits first.'),
        mcq('What is a risk of PgBouncer transaction pooling?',
            'Code relying on session-level settings can break between transactions.',
            ['It reserves one server connection for each client session.',
             'It disables transactions entirely for every pooled client.',
             'It blocks prepared statements in every possible pooler configuration too.'],
            'The server connection is released after each transaction. Session pooling is the mode that reserves a connection '
            'per client session, and prepared-statement support depends on the feature and configuration.'),
    ],
    'sd-10': [
        mcq('Does a publisher confirm mean the report has been generated?',
            'No. It confirms the broker accepted the message, not that work finished.',
            ['Yes. The broker confirms only after the consumer finishes the work.',
             'Yes, provided the queue was declared durable by the producer.',
             'No. It confirms the consumer received it, but not that it succeeded.'],
            'Publisher confirms and consumer acknowledgements cover different stages; one does not imply the other.'),
        mcq('Why is oldest-job age a useful queue metric?',
            'It shows how long accepted work has waited; a count ignores job cost.',
            ['It is cheaper for the broker to compute than the queue length.',
             'It measures how busy the worker CPUs are at that moment.',
             'It replaces the error rate as the main signal of overall worker health.'],
            'Ten expensive jobs may be worse than a thousand cheap ones.'),
        mcq('A worker commits the business effect, then crashes before acknowledging the message. What happens next?',
            'The message can be redelivered, so the repeat must spot the result.',
            ['The work is lost for good, because the message was never acknowledged.',
             'The broker sees the database commit and drops the message.',
             'The producer is asked to publish a fresh copy of the job.'],
            'Acknowledging after the effect can allow duplicates; acknowledging before it can lose work after a crash.'),
        mcq('Ten workers each process one job per second while 1,200 jobs/min arrive for ten minutes. How large is the backlog afterwards?',
            '6,000 jobs', ['12,000 jobs', '600 jobs', 'No backlog'],
            'Capacity is 600 jobs/min, so the queue grows by 600 jobs a minute for ten minutes.'),
        mcq('You then run 15 workers and arrivals return to 600/min. How long does the 6,000-job backlog take to drain?',
            '20 minutes', ['10 minutes', '40 minutes', 'About 7 minutes'],
            '15 workers complete 900 jobs/min, leaving 300/min spare: 6,000 ÷ 300 = 20 minutes.'),
        multi('How should a job queue handle a job with malformed input? Select all that apply.',
              [('Cap the number of attempts it gets.', True),
               ('Classify the error as not retryable.', True),
               ('Move it to a visible failed-job path.', True),
               ('Retry it forever with exponential backoff.', False)],
              'Retrying malformed input wastes capacity. Failures need a visible dead-letter or failed-job path.'),
    ],
    'sd-11': [
        mcq('Does a strongly consistent object store guarantee fresh CDN responses?',
            'No. The CDN may keep serving its cached copy under its own policy.',
            ['Yes. Each object write invalidates every CDN copy automatically.',
             'Yes, as long as uploads use PUT rather than a multipart upload.',
             'No. Strong consistency applies only to reads made through a CDN.'],
            'Read-after-write consistency in the object store does not refresh a downstream CDN.'),
        mcq('Why keep an upload record in a pending state?',
            'It separates transfer from validation, so stalled uploads can be recovered.',
            ['It hides the uploaded file from its owner until an administrator reviews it.',
             'Object stores refuse any upload that lacks a matching pending record.',
             'It lowers storage costs by delaying when the bytes are billed.'],
            'If the upload succeeds but the metadata update fails, the user still sees pending and a reconciler can finish or retire it.'),
        mcq('A teacher replaces a worksheet at the same URL and some students still see the old one. Which publish flow gives predictable version identity?',
            'Upload a new immutable key, validate it, then switch the metadata.',
            ['Overwrite the object in place so the URL never has to change.',
             'Switch the metadata pointer first, then upload the new object.',
             'Use an unguessable key for the file and email the new link.'],
            'Immutable, versioned keys make replacement explicit; old cached URLs keep identifying the old bytes. Switch the metadata atomically.'),
        mcq('What happens if the metadata pointer switches before the new object is ready?',
            'Readers can receive missing or invalid content.',
            ['Nothing; the CDN waits until the object exists.',
             'The old object is served automatically instead.',
             'The upload is cancelled and has to start again.'],
            'Publication has to follow object readiness.'),
        multi('Which statements about direct-to-storage uploads are correct? Select all that apply.',
              [('They reduce the bandwidth the application servers carry.', True),
               ('The upload capability should be short-lived and scoped.', True),
               ('The uploaded object still needs validation afterwards.', True),
               ('An obscure object key is enough protection for private files.', False)],
              'An obscure key is not permission. Private content needs access control at delivery time.'),
    ],
    'sd-12': [
        mcq('Why is created_at alone often an insufficient cursor key?',
            'Rows can share a timestamp, so a unique tiebreaker is needed.',
            ['Timestamps cannot be compared reliably inside most SQL databases.',
             'created_at is rewritten whenever the row is read again.',
             'Cursors are only allowed to use the table\'s primary key.'],
            'Sort by (created_at, id) and continue after the last tuple.'),
        mcq('Does keyset pagination guarantee an immutable result set?',
            'No. Updates and deletions still change what later pages show.',
            ['Yes. The cursor freezes the collection at its first page.',
             'Yes, once the server signs the cursor so it cannot be altered.',
             'No. Keyset pages are random samples, so no order is kept.'],
            'A cursor defines continuation, not membership. Snapshot semantics need a separate design.'),
        mcq('Page one returned the 10:03 and 10:02 items. A 10:04 item arrives. What does OFFSET 2 return first on page two?',
            'The 10:02 item, shown a second time.', ['The 10:01 item, the oldest one.', 'The 10:04 item, the newest one.', 'An empty page, since none are left.'],
            'The new item shifts every offset by one, repeating an item. A cursor after the unique (10:02, id) pair continues with older entries.'),
        mcq('Why can large OFFSET values be expensive?',
            'The skipped rows still have to be read and counted.',
            ['OFFSET disables every index the query could otherwise use.',
             'OFFSET takes a lock on the whole table while it runs.',
             'All the skipped rows are sent to the client, then dropped.'],
            'Keyset pagination avoids this but usually cannot jump straight to page 10,000.'),
        multi('What should the server check when it receives a pagination cursor? Select all that apply.',
              [('It matches the same tenant, filters and sort order.', True),
               ('The caller is still authorized, checked on every page.', True),
               ('It was not tampered with, if tampering matters.', True),
               ('Nothing, because an opaque encoding makes it safe.', False)],
              'Treat a cursor as untrusted input. Opaque encoding alone provides neither authorization nor tamper protection; '
              'use a signature or server-side cursor state when tampering matters.'),
    ],
    'sd-31': [
        mcq('Does consistent hashing stop a single hot key from overloading its node?',
            'No. Every request for that key still reaches the one node that owns it.',
            ['Yes. Virtual nodes spread a single key over several servers.',
             'Yes, once the cluster rebalances so the key has more room.',
             'No. Consistent hashing always sends every hot key to the newest node added.'],
            'Partitioning spreads distinct keys; it cannot split one. Cache the key\'s reads or split its writes across suffixed sub-keys.'),
        mcq('Why do virtual nodes help when a node fails?',
            'The failed node\'s keys scatter across many survivors, not one neighbor.',
            ['Every node keeps a full copy of every key, so nothing is lost.',
             'No key has to move when a node fails, so there is no traffic.',
             'The failed node keeps serving its keys through its remaining virtual nodes.'],
            'With one ring position per node, a failed node\'s whole load falls on its single clockwise neighbor.'),
        mcq('A cache holds 1,000,000 keys on four nodes placed by hash(key) mod N. A fifth node joins. About how many keys change node?',
            'About 800,000', ['About 200,000', 'About 250,000', 'None of them'],
            'A key stays only when its hash leaves the same remainder mod 4 and mod 5, which happens for 4 of every 20 hash values. '
            'For a cache, the moved keys become near-simultaneous misses.'),
        mcq('The same cluster uses a consistent-hash ring with many virtual nodes per server. When the fifth node joins, which keys move?',
            'About 200,000, the new node\'s share, taken from all four old nodes.',
            ['About 800,000, reshuffled evenly across all five of the ring\'s nodes.',
             'About 250,000, all taken from the one clockwise neighbor.',
             'None, until each key\'s cache entry expires on its old node.'],
            'A joining node takes over only the keys on the arcs it lands on. No key moves between two nodes that both stayed.'),
        mcq('A range-partitioned table is keyed by event timestamp. Why does its write throughput stop scaling?',
            'Every new row lands in the last range, so one partition takes all writes.',
            ['Range partitions cannot use timestamp values as their partition keys at all.',
             'Timestamps all hash to the same value, so one partition wins.',
             'Each range scan locks the whole table and blocks the inserts.'],
            'No split point divides that write load. Lead the key with a high-cardinality field such as a user ID, or hash-shard it and accept that ordered reads must merge shards.'),
        multi('Which statements about hash partitioning are correct? Select all that apply.',
              [('It spreads sequential keys evenly across the partitions.', True),
               ('An ordered scan must ask every partition and merge results.', True),
               ('It keeps neighboring keys together, so prefix scans stay local.', False),
               ('With hash mod N, adding a node moves only its fair share.', False)],
              'Hashing trades sort order for an even spread. Placement by hash mod N ties each key to the node count, so most keys move when N changes.'),
    ],
}

ADVANCED = {
    'sd-13': [
        mcq('Three nested layers each make up to three attempts. How many calls can reach the deepest dependency?',
            '27', ['9', '81', '6'],
            '3 × 3 × 3 = 27. One retry owner or a propagated retry budget prevents the multiplication.'),
        mcq('A payment request times out. May the client treat the payment as failed?',
            'No. It may have committed; check durable state with the same identity.',
            ['Yes. A timeout means the server never processed the request.',
             'Yes, but only after one more retry that uses a brand-new operation key.',
             'No. It succeeded, because timeouts only happen after a commit.'],
            'A timeout is the caller deciding it has waited long enough, not a message that nothing happened. Inspect durable state or reconcile using the original operation identity.'),
        mcq('A request has a 1,000 ms deadline. Attempt one took 300 ms, backoff waited 100 ms, attempt two took 400 ms. Should the client start a third 400 ms attempt?',
            'No. Only 200 ms remain for more work and for the response.',
            ['Yes. Its 400 ms per-attempt timeout still allows one more try.',
             'Yes. Adding jitter extends the deadline by the backoff wait.',
             'No. A client may only ever retry once, whatever the deadline.'],
            'Bound retries by the total deadline as well as per-attempt limits.'),
        mcq('What does jitter add to exponential backoff?',
            'It spreads clients out so they do not all retry at the same time.',
            ['It shortens each wait so that every retry happens sooner.',
             'It caps the number of attempts that each client is allowed to make.',
             'It makes a non-idempotent operation safe to send again.'],
            'Fixed retry intervals synchronize clients after an outage.'),
        multi('Which belong in a retry policy? Select all that apply.',
              [('A total deadline across all the attempts.', True),
               ('A cap on the number of attempts made.', True),
               ('Retrying only errors the contract permits.', True),
               ('Immediate retries of every error, for speed.', False)],
              'Every retry adds work exactly when a dependency may be struggling. Idempotency protects repeated effects, not load.'),
    ],
    'sd-14': [
        mcq('Is a content hash always a valid substitute for a client operation key?',
            'No. Two separate, intended operations can have identical payloads.',
            ['Yes. Identical request content always means it is a retry.',
             'Yes, provided the hash function is a strong one like SHA-256.',
             'No. Hash values collide too often to identify a request safely.'],
            'Hashing content alone can merge two intentional identical purchases.'),
        mcq('Why must idempotency-key retention be documented?',
            'A duplicate that arrives after the keys expire is treated as new.',
            ['Keys are kept forever, so retention only matters for later audits.',
             'The retention period also sets the timeout for each request.',
             'It is a compliance formality with no effect on behavior.'],
            'Duplicate suppression only covers the period and scope for which identifying state exists. Choose retention from the retry and replay horizon, then communicate it.'),
        mcq('A caller reuses an idempotency key with a different amount. What should the service do?',
            'Reject the reuse after comparing the stored request fingerprint.',
            ['Silently replay the result that was stored for the original request.',
             'Process it as a brand-new operation with the new amount.',
             'Overwrite the stored operation so it uses the new amount.'],
            'A reused key with changed input should not silently replay the wrong result.'),
        mcq('Transaction T claims key (tenant7, award, abc), awards a credit, records the result and commits, but its response is lost. Duplicate U arrives. What happens?',
            'U loses the unique-key claim and returns T\'s committed result.',
            ['U awards a second credit because T\'s response never arrived.',
             'U blocks until T\'s lost response is eventually delivered.',
             'U deletes T\'s key record and then starts the award over.'],
            'This works because the key record and the effect share one transaction. An email sent inside T would not become transactional.'),
        mcq('A worker crashes after a remote provider succeeded but before recording it locally. What should recovery do?',
            'Ask the provider, or resend with the same key, before recording it.',
            ['Mark the operation failed and retry it with a new provider key.',
             'Mark it succeeded, since a pending row implies the call worked.',
             'Delete the pending row so the client is free to try again.'],
            'A local pending row cannot prove whether the remote effect happened. Query the provider, or repeat under its deduplication contract with the same operation key.'),
    ],
    'sd-15': [
        mcq('Does transactional Kafka processing automatically make an external SQL update exactly once?',
            'No. The SQL update needs its own idempotent or coordinated commit.',
            ['Yes. Kafka transactions extend to every downstream system.',
             'Yes, if every consumer is set to read only committed records.',
             'No. Kafka transactions only work when there is a single partition.'],
            'Kafka transactions can combine output records and consumed offsets; they do not commit an unrelated database.'),
        mcq('Can messages delivered in order produce effects out of order?',
            'Yes. Parallel workers and retries can change completion order.',
            ['No. Delivery order always equals the order of the effects.',
             'Yes, but only when the broker loses messages and resends them.',
             'No, as long as each worker acknowledges messages in order.'],
            'Include entity versions or sequence numbers and define what consumers do with gaps or stale updates.'),
        mcq('A consumer increments a SQL counter for event e42, then crashes before committing its broker offset. Which design keeps replay from counting e42 twice?',
            'Record e42 as processed in the same SQL transaction as the increment.',
            ['Commit the broker offset first, before running the SQL increment at all.',
             'Retry the increment faster so the crash window gets smaller.',
             'Put every event in the whole system into one global order.'],
            'A unique processed-events row written with the increment lets replay skip e42. Committing the offset first only changes the failure into a missing increment.'),
        mcq('Version 12 of a search document arrives before version 11. When is rejecting version 11 safe?',
            'When each event carries the complete versioned state.',
            ['Always, because older versions are never needed again.',
             'Never, because events must be applied in arrival order.',
             'When events are deltas such as "add one to quantity".'],
            'Discarding an earlier delta can lose a required change. The payload semantics decide the rule.'),
        multi('Which statements about delivery guarantees are correct? Select all that apply.',
              [('At-least-once processing can repeat work during recovery.', True),
               ('At-most-once processing can lose work after a crash.', True),
               ('Ordering is usually scoped to one partition or stream.', True),
               ('Exactly-once is a broker setting that covers all effects.', False)],
              'Exactly-once is meaningful only inside a defined protocol boundary.'),
    ],
    'sd-16': [
        mcq('Does the outbox pattern remove duplicate event delivery?',
            'No. A relay can still republish an event after a crash.',
            ['Yes. Each outbox row is published exactly once by design.',
             'Yes, when change data capture replaces the polling relay.',
             'No. It removes duplicates only when consumers commit offsets.'],
            'The outbox closes the local dual-write gap. Consumers must still handle duplicates, helped by an event ID.'),
        mcq('Why store a schema version on each event?',
            'Consumers can interpret payloads as producers change them.',
            ['Brokers reject any event that is missing a schema version.',
             'It orders events correctly across different partitions.',
             'It encrypts the payload so only matching consumers read it.'],
            'Producers and consumers evolve independently. Explicit domain events give a more stable contract than raw table changes.'),
        mcq('What does the outbox pattern make atomic?',
            'The business change and the intent to publish it.',
            ['Publishing the event and consuming it downstream.',
             'The broker acknowledgement and the database commit.',
             'The event and the email that it eventually triggers.'],
            'Both are written in one local transaction. A relay later publishes committed events by polling or change data capture.'),
        mcq('The broker is down for an hour. What happens to orders confirmed in that hour?',
            'Their events wait in the outbox and go out once a relay works.',
            ['Their events are lost because the broker never received them.',
             'The order transactions roll back until the broker returns.',
             'Their events are published twice later, as a precaution.'],
            'The database still holds the publication intent, provided it is retained until a relay publishes it.'),
        mcq('Why is deleting every outbox row older than one hour unsafe?',
            'Age does not prove an event was published; follow relay progress.',
            ['It is safe, since relays publish within a few seconds anyway.',
             'Deleting rows takes a lock on the orders table while it runs.',
             'Rows older than an hour are only needed for compliance audits.'],
            'A relay may be offline for hours. Retention has to follow relay progress and replay guarantees, with lag monitored against retained data.'),
    ],
    'sd-17': [
        mcq('Does compensation restore every outside observer to the original state?',
            'No. Sent notifications, fees and observations may be irreversible.',
            ['Yes. Compensation erases the original action from history.',
             'Yes, whenever the saga is orchestrated rather than choreographed.',
             'No. Compensation is only possible within a single database.'],
            'Compensation is a new business action: a refund differs from pretending no charge happened.'),
        mcq('Why persist the saga coordinator\'s state?',
            'A restarted coordinator must resume without repeating or forgetting steps.',
            ['The saved state is only ever used for analytics dashboards and weekly reports.',
             'Message queues refuse to deliver commands to a stateless sender.',
             'Persisting the state makes each individual saga step run faster.'],
            'Durable state, idempotent commands and explicit recovery paths let a restarted coordinator resume or repair the workflow without contradictory actions.'),
        mcq('An order is payment_pending when the provider call times out. What should the saga do?',
            'Reconcile the provider operation by its stable identity.',
            ['Mark the payment as declined and release the inventory.',
             'Release the inventory and charge the customer once again.',
             'Confirm the booking optimistically and fix it up later.'],
            'A timeout leaves the outcome unknown, so do not treat it as a decline.'),
        mcq('Payment succeeds late, after the inventory hold expired and the item went to someone else. What next?',
            'Re-reserve if allowed; otherwise void or refund the payment.',
            ['Confirm the order anyway, since the customer has now paid.',
             'Ignore the late payment, because the hold already expired.',
             'Delete the payment record so the ledger shows no charge at all.'],
            'Never confirm unavailable inventory. Record compensation progress until it succeeds or enters manual repair.'),
        multi('Which statements about sagas are correct? Select all that apply.',
              [('Orchestration uses a coordinator that commands each step.', True),
               ('Choreography has services react to events with no controller.', True),
               ('Compensation is a new business action, not erased history.', True),
               ('A saga isolates each workflow from the others until it ends.', False)],
              'A saga usually does not provide isolation: another workflow may see reserved inventory before final confirmation.'),
    ],
    'sd-18': [
        mcq('Can a requests-per-second limit alone protect a dependency whose latency suddenly rises tenfold?',
            'Not reliably. Slow calls pile up in flight, so bound concurrency too.',
            ['Yes. A rate limit bounds every kind of resource the service uses.',
             'Yes, provided the limit is applied separately for each tenant.',
             'No. Rate limits only apply to writes, not to reads that slow down.'],
            'A service can have a low request rate but high concurrency when calls become slow. Bound waiting work as well.'),
        mcq('Why can a fallback make an outage worse?',
            'The fallback path may cost more or have less capacity than normal.',
            ['Fallbacks always return errors, which the clients then retry.',
             'Enabling a fallback switches off any load shedding in place.',
             'Fallbacks run only on clients, so servers cannot control them.'],
            'Switching every cache miss to SQL can amplify an incident. Fallbacks need their own budget.'),
        mcq('Arrivals reach 1,400 jobs/s while workers sustain 1,000/s. How long does a 2,000-job buffer take to fill from empty?',
            'About 5 seconds.', ['About 2 seconds.', 'About 1.4 seconds.', 'It never fills.'],
            'The deficit is 400/s: 2,000 ÷ 400 = 5 s. A bigger buffer only postpones the failure.'),
        mcq('Jobs expire after three seconds. Why is a very deep queue a problem?',
            'Workers spend capacity on jobs whose results nobody can use.',
            ['Deep queues always drain faster than shallow ones under load.',
             'Expired jobs are retried automatically, doubling the work.',
             'Queue depth has no effect on how long any single job waits.'],
            'Admission and prioritization should reflect the usefulness deadline.'),
        mcq('One noisy tenant uses all the capacity under a single global limit. What gives more control?',
            'Per-tenant budgets under a shared overall ceiling.',
            ['A larger global queue that holds more of the work.',
             'Retrying every rejected request immediately.',
             'Removing the global limit so tenants self-regulate.'],
            'Poor prioritization can also starve low-priority tenants, so budgets need a documented policy.'),
        multi('Which pairings of control and what it bounds are correct? Select all that apply.',
              [('A rate limit bounds arrivals over time.', True),
               ('A concurrency limit bounds in-flight work.', True),
               ('A queue limit bounds work waiting to start.', True),
               ('A rate limit bounds memory held by slow calls.', False)],
              'These controls address different resources.'),
    ],
}

PRODUCTION = {
    'sd-19': [
        mcq('For a 99.5% target over 200,000 eligible events, how many bad events are allowed?',
            '1,000', ['995', '10,000', '100'],
            '200,000 × (1 − 0.995) = 1,000.'),
        mcq('Is an error budget permission to ignore every error below the threshold?',
            'No. Severe or concentrated failures can need action inside budget.',
            ['Yes. Any error that fits inside the budget is acceptable.',
             'Yes, until the measurement window resets at the month end.',
             'No. An error budget means that every error must be fixed at once.'],
            'An error budget is a decision tool. Severe correctness or security failures, or failures concentrated on some users, may need action anyway.'),
        mcq('An SLO requires 99.9% of eligible requests to be good over 30 days. An interval has a 1% bad fraction. What is the burn rate?',
            '10', ['1', '0.1', '100'],
            'Burn rate = observed bad fraction ÷ allowed bad fraction = 0.01 ÷ 0.001.'),
        mcq('If that burn rate persists and traffic is uniform, roughly how soon is a fresh 30-day budget consumed?',
            'About 3 days.', ['About 10 days.', 'About 30 days.', 'About 3 hours.'],
            '30 days ÷ 10 = 3 days. With variable traffic, the event counts decide consumption.'),
        mcq('A dashboard endpoint returns HTTP 200 quickly but leaves out the learner\'s saved progress in 2% of responses. How should the indicator count those?',
            'As bad events, since they break the response contract.',
            ['As good events, since the status code returned was 200.',
             'As good events, since every one of them was served fast.',
             'Not at all, since missing data is a client-side problem.'],
            'A status-code-only indicator misses this failure. Define success to include the required data.'),
    ],
    'sd-20': [
        mcq('Why should request IDs usually not be metric labels?',
            'Unbounded values multiply time series; logs and traces suit IDs.',
            ['Metric systems cannot store string values as label values.',
             'Request IDs are secrets and must never leave the server.',
             'Label values are limited to numbers in most metric systems today.'],
            'Prefer bounded labels such as route templates and outcome classes. Nearly unbounded values multiply series and storage cost.'),
        mcq('Does a fast acceptance endpoint prove a background workflow is fast?',
            'No. Queue waiting and execution can dominate after acceptance.',
            ['Yes. Acceptance latency is the same as end-to-end latency.',
             'Yes, as long as the endpoint answers quickly with 202 Accepted.',
             'No. Background work is always slower than the web request.'],
            'Track acceptance latency, queue age, processing latency and end-to-end completion separately.'),
        mcq('An export\'s acceptance span takes 70 ms, it waits 85 s in the queue, and the worker takes 4.93 s. What reveals the user\'s 90-second wait?',
            'End-to-end completion latency, alongside queue age.',
            ['The web server latency chart for the export route.',
             'The CPU usage of the workers running the export.',
             'The broker throughput in messages per second.'],
            'The web server chart looks healthy while the user waits.'),
        mcq('Queue age is rising while workers sit idle. What does that suggest first?',
            'A scheduling or consumption problem on the worker side.',
            ['Provider throttling that slows down each delivery attempt.',
             'Too many workers competing with each other for jobs.',
             'An acceptance endpoint that is answering too quickly.'],
            'Active attempts receiving throttle responses would point toward provider limits instead. Validate either hypothesis with worker and dependency signals.'),
        multi('Which statements about telemetry signals are correct? Select all that apply.',
              [('Metrics summarize measurements over time.', True),
               ('Logs record individual events and their details.', True),
               ('Traces link timed operations across one request.', True),
               ('A trace ID can stand in for a durable operation ID.', False)],
              'Trace relationships express execution structure; durable business IDs identify an operation across retries, reconciliation and days of processing.'),
    ],
    'sd-21': [
        mcq('Why can a constant-virtual-user test hide overload?',
            'As responses slow, each virtual user sends fewer requests.',
            ['Virtual users ignore errors, so failures never get counted.',
             'Constant-user tests have no way to measure response latency.',
             'The load generator always crashes before the service does.'],
            'The offered arrival rate falls exactly when the service struggles. This is coordinated omission.'),
        multi('What must accompany a throughput result? Select all that apply.',
              [('The workload assumptions behind the test.', True),
               ('The offered load, not just the achieved load.', True),
               ('The latency and error outcomes observed.', True),
               ('The virtual-user count, with nothing else.', False)],
              'Report the environment and relevant resource or dependency limits too.'),
        mcq('100 virtual users each repeat a request as soon as it finishes. Response time rises from 100 ms to 1 s. What happens to the offered load?',
            'It falls from about 1,000 to about 100 requests/s.',
            ['It stays at about 1,000 requests/s throughout.',
             'It rises from about 1,000 to about 10,000 requests/s.',
             'It falls from about 1,000 to zero requests/s.'],
            'The slowdown reduced test pressure tenfold. An arrival-rate test preserves the intended demand.'),
        mcq('Which kind of test exposes leaks and slow growth?',
            'A soak test.', ['A stress test.', 'A recovery test.', 'A smoke test.'],
            'Stress tests find limits; soak tests expose growth, leaks and maintenance effects; recovery tests measure the return to health.'),
        mcq('In an open workload model, how is new work scheduled?',
            'Independently of when earlier work completes.',
            ['Only after each earlier iteration has finished.',
             'Only while the service under test is idle.',
             'At a rate set by the service\'s response time.'],
            'Neither model is universally correct; pick the one that matches the real workload.'),
    ],
    'sd-22': [
        mcq('Does deploying the previous application image reverse a database migration?',
            'No. Schema and data changes persist after the old image returns.',
            ['Yes. The old image carries the old schema and restores it.',
             'Yes, provided the migration originally ran in a transaction.',
             'No. Migrations can never be undone once they have been applied.'],
            'The old code may no longer be compatible with the new data. Prefer a forward repair when a rollback would misread newer data.'),
        mcq('Why validate a backfill before dropping the old field?',
            'Bad or missing values would otherwise become permanent data loss.',
            ['PostgreSQL refuses to drop a column that has no validated backfill.',
             'Validating the backfill first makes the column drop run faster.',
             'Validation marks the new column NOT NULL, which the drop requires.'],
            'Missing, stale or wrongly transformed values become user-visible once the source is gone. Verify counts and semantics before contracting.'),
        mcq('You are replacing full_name with display_name using expand, migrate, contract. What comes first?',
            'Add the new nullable display_name column.',
            ['Drop full_name once the new code is live.', 'Switch all reads over to display_name.',
             'Backfill display_name from full_name.'],
            'Add it while the old code still works. Then write both, backfill in batches, verify, switch reads, and remove the old column only when nothing needs it.'),
        mcq('Why run a backfill in small, restartable batches?',
            'It competes with live queries and replication, so it must be throttled.',
            ['PostgreSQL rejects any single UPDATE statement that touches a large batch.',
             'Small batches let the backfill skip the validation step later.',
             'Batching makes the backfill reversible with a single rollback.'],
            'Watch lag and locks while it runs, and avoid overwriting a newer display_name.'),
        mcq('An event field changes from a string amount to integer minor units. What must happen before producers emit the new form?',
            'Consumers are upgraded to read both the old and new forms.',
            ['The old string field is dropped from the event schema.',
             'Historical events in the old format are deleted first.',
             'Consumers are paused until every producer has switched.'],
            'Version the event contract and keep historical replay working.'),
    ],
    'sd-23': [
        mcq('Does an unguessable UUID authorize access to a record?',
            'No. It makes guessing harder but is not a permission check.',
            ['Yes. Only the record\'s owner could ever know its UUID.',
             'Yes, as long as the UUID is only ever sent over HTTPS.',
             'No. UUIDs are predictable, so they must be encrypted first.'],
            'Check access whenever client-supplied identifiers select records.'),
        mcq('Is enabling row-level security enough when the application connects as a superuser?',
            'No. Superusers bypass row security, so the role matters too.',
            ['Yes. Row-level security applies to every role, superusers included.',
             'Yes, once policies are written for every table in the schema.',
             'No. Row-level security only works with connection pooling off.'],
            'Superusers, BYPASSRLS roles and normally table owners bypass policies, so the role and policy configuration are part of the guarantee.'),
        mcq('Tenant A and tenant B each have a report numbered 17. What is wrong with the cache key report:17?',
            'It is ambiguous: one tenant can get the other tenant\'s report.',
            ['Nothing is wrong, as long as the SQL query filters by tenant.',
             'Cache keys cannot contain numbers, so it will be rejected.',
             'The key is too short, so it will never produce a cache hit.'],
            'Scope the key to the authorized tenant and representation, and recheck required permissions.'),
        mcq('A queued export job takes tenant_id from the request body. What is the risk?',
            'A caller can pick another tenant\'s id and export their data.',
            ['None, because the job runs in the background, not the request.',
             'The job may run twice, since the id arrives with each retry.',
             'The export runs slower because the id must be parsed twice.'],
            'The job must carry a trusted tenant identity and the right authorization policy.'),
        multi('Which statements are correct? Select all that apply.',
              [('Authentication answers who is making the request.', True),
               ('Authorization decides if this identity may take this action.', True),
               ('Tests run as a superuser can hide row-policy mistakes.', True),
               ('A valid login is enough to read any record in its tenant.', False)],
              'Authorization covers this action on this resource now. Use application roles representative of production when testing.'),
    ],
    'sd-24': [
        mcq('Why is a current replica not a substitute for historical backups?',
            'It can faithfully copy a destructive or corrupting change.',
            ['Replicas cannot be read while the primary is having an outage.',
             'Replicas are always hours behind the primary database.',
             'Replicas store data in a format that backups cannot use.'],
            'A backup preserves a recoverable past; a replica copies the present.'),
        mcq('What makes a recovery time objective (RTO) credible?',
            'A timed, representative drill of the whole recovery path.',
            ['A record of nightly backup jobs that finished successfully.',
             'The time it takes to start a replacement database machine.',
             'The restore speed the storage vendor publishes for its disks.'],
            'The drill covers data restoration, validation, dependencies and traffic restoration. A successful backup job alone is not proof of recoverability.'),
        mcq('Corruption began at 14:02. The latest base backup is from 02:00 and archived logs run to 14:05. Where should the restore stop?',
            'At a consistent point just before the damaging transaction.',
            ['At 14:05, the latest point that the archived logs can reach.',
             'At 02:00, the moment the base backup itself was taken.',
             'At 14:05, and then delete the corrupted rows by hand.'],
            'Restoring to the latest point would replay the corruption. Every required log must exist.'),
        mcq('The restore takes 45 minutes and verification plus routing another 20. Starting the machine took 2. What is the observed recovery time at least?',
            '65 minutes', ['2 minutes', '45 minutes', '20 minutes'],
            'Measure each phase; the recovery time is not the machine start time.'),
        multi('Which statements are correct? Select all that apply.',
              [('RPO is the tolerated data loss, measured in time.', True),
               ('RTO is the tolerated time to restore service.', True),
               ('A backup in the same credential domain can vanish too.', True),
               ('A logical dump can serve as the base for WAL replay.', False)],
              'Point-in-time recovery combines a physical base backup with a continuous sequence of write-ahead logs.'),
    ],
}

EXPERT = {
    'sd-25': [
        mcq('Does serializability alone require a later transaction to see every earlier completed transaction in wall-clock order?',
            'No. That real-time rule belongs to strict serializability.',
            ['Yes. Serializability always follows wall-clock commit order.',
             'Yes, but only for transactions that perform no writes.',
             'No. Serializability only constrains single-row operations.'],
            'Serializability means equivalent to some serial order, not necessarily the real-time one.'),
        mcq('Under linearizability, can a stale read be legal when it overlaps a write?',
            'Yes. It can be ordered before the overlapping write.',
            ['No. Every read must return the most recent write.',
             'Yes, but only if the replicas\' clocks are synchronized.',
             'No. Overlapping operations are not allowed at all.'],
            'Operations that complete before another starts impose stronger constraints.'),
        mcq('A register holds 0. A writes 1 and gets success at t2. B starts a read at t3, after t2, and gets 0. No other write happened. Is this history linearizable?',
            'No. B began after A\'s write finished, so it must see 1.',
            ['Yes. Replicas are allowed to lag behind for a while.',
             'Yes, as long as B\'s clock is running behind A\'s clock.',
             'No. A register can only ever be read by its writer.'],
            'Write down invocation and completion intervals rather than sorting by client timestamps.'),
        mcq('A workspace must keep at least one owner. Two owners each read that two owners exist, then each removes their own owner role. Why don\'t per-key atomic writes prevent this?',
            'The rule spans two keys, and both reads come before either write.',
            ['Atomic writes are not durable, so one of the removals is lost.',
             'The two writes conflict on the same key and one is rejected.',
             'The database silently drops one write when two arrive together.'],
            'Each write is atomic, but the invariant covers both memberships. Protect the shared predicate with a suitable '
            'isolation or locking strategy, or route the decision through one authoritative membership record.'),
        multi('Which statements are correct? Select all that apply.',
              [('Read-your-writes is a session guarantee, not linearizability.', True),
               ('Eventual convergence sets no finite bound on staleness.', True),
               ('During a partition, linearizable ops cannot stay available on all sides.', True),
               ('Choosing R + W > N is enough, alone, to prove a protocol linearizable.', False)],
              'Quorum arithmetic alone is not a proof: write ordering, version selection and failure behavior matter.'),
    ],
    'sd-26': [
        mcq('Does a timeout prove the leader is dead?',
            'No. It may be slow or cut off; the protocol must stay safe anyway.',
            ['Yes. A healthy leader always answers within the timeout.',
             'Yes, as long as at least two followers agree that it timed out.',
             'No. In Raft, only a human operator can declare a leader dead.'],
            'Failure detectors can be wrong. Elections and term rules keep safety despite false suspicions.'),
        mcq('Why must membership changes be coordinated?',
            'Old and new majorities could otherwise decide without overlapping.',
            ['New members would otherwise be unable to read the replicated log.',
             'Coordinating the change is what makes leader elections faster.',
             'Leaders refuse to send entries to any member they do not know.'],
            'Replacing {A,B,C} with {C,D,E} by hand lets {A,B} and {D,E} each act as a majority.'),
        mcq('Five voting members split 3–2. Which side can commit new entries?',
            'The three-member side, if it has an eligible leader.',
            ['Both sides, independently, until the partition heals.',
             'Neither side, until all five members can talk again.',
             'The two-member side, if it still holds the old leader.'],
            'Five voters need three votes. The minority cannot commit on its own.'),
        mcq('A three-voter cluster has one failed member. Why is adding an empty node as a fourth voter risky?',
            'Majority rises to three; with one down and one behind, progress stops.',
            ['A cluster with four voters can never elect a leader at all.',
             'The new, empty voter immediately becomes the cluster leader.',
             'Adding any voter forces a full restart of every member of the whole cluster.'],
            'Keep the working quorum, use the supported learner or replacement workflow, and wait for catch-up.'),
        mcq('What is a learner in Raft-based systems?',
            'A non-voting member that catches up before promotion.',
            ['A candidate that has just lost an election for leader.',
             'A follower that votes in elections but can never lead.',
             'A replica that accepts writes locally and syncs later.'],
            'Learners avoid increasing the voting quorum prematurely.'),
    ],
    'sd-27': [
        mcq('Can a prepared participant safely abort just because its timer expired?',
            'No. A commit decision may exist; it must follow recovery rules.',
            ['Yes. In two-phase commit, any timeout always means abort.',
             'Yes, as long as it has not heard from the other participants.',
             'No. It must commit on its own once its timer has expired.'],
            'A prepared participant promised not to choose an outcome independently.'),
        mcq('Does consensus automatically turn arbitrary database writes into a distributed transaction?',
            'No. Atomic commit and isolation need their own protocol design.',
            ['Yes. A replicated log is already a full distributed transaction.',
             'Yes, provided every write reaches a majority quorum first.',
             'No. Consensus can only order reads, never order writes.'],
            'Consensus orders agreed state. Atomicity across participants and isolation are separate problems.'),
        mcq('The coordinator durably records commit, tells store A, and crashes before telling store B. What must B do?',
            'Stay prepared, recover the commit decision, then commit.',
            ['Abort once its own wait timer runs out, to free locks.',
             'Commit on its own initiative without asking anyone.',
             'Ask store A to roll back so both stores stay in step.'],
            'A has already committed. B cannot abort just because it waited.'),
        mcq('What does a participant promise when it votes "prepared" in two-phase commit?',
            'It durably saved enough to finish and won\'t decide alone.',
            ['It has already committed its own part of the whole transaction.',
             'It will abort on its own if the coordinator is slow.',
             'It has released its locks so other work can proceed.'],
            'Prepared transactions keep their locks, which can block ordinary work.'),
        multi('You need to move credits between two balances. Which statements are correct? Select all that apply.',
              [('One local transaction can protect both balances in one store.', True),
               ('Two-phase commit can leave participants blocked while one is down.', True),
               ('A saga can expose the debit before the credit happens.', True),
               ('Two-phase commit defines the isolation level automatically.', False)],
              'Atomicity does not define isolation. Choose based on the invariant and availability needs.'),
    ],
    'sd-28': [
        mcq('Does a distributed lock physically stop an expired worker?',
            'No. It may keep going; the resource must reject stale authority.',
            ['Yes. When the lease expires the lock service kills the process.',
             'Yes, as soon as the worker stops sending its heartbeats.',
             'No. It stops the worker only if clocks are synchronized.'],
            'A paused process can wake up later and act on an old belief.'),
        mcq('Does a monotonic clock order events on different machines?',
            'No. It measures elapsed time only within its own machine.',
            ['Yes. Monotonic clocks never go backwards on any machine.',
             'Yes, once all the machines are synchronized through NTP.',
             'No. Monotonic clocks can jump backwards when NTP adjusts.'],
            'Monotonic clocks measure local elapsed time and never step backwards; they do not establish a universal order.'),
        mcq('A worker holding epoch 41 stalls, its lease expires, and a worker with epoch 42 publishes. Worker 41 resumes and tries to publish. What should happen?',
            'The store compares epochs and rejects the epoch-41 write.',
            ['The later write wins, so worker 41\'s result replaces 42.',
             'Both results are kept, and readers pick the newest one.',
             'The lock service blocks worker 41 before it reaches the store.'],
            'Checking only that a worker once held a lease lets the stale result overwrite the new one.'),
        mcq('Why is checking the lease in one call and then writing in a separate call unsafe?',
            'Ownership can change between the check and the write.',
            ['Making two calls doubles the latency of each publication.',
             'Leases are write-only, so they cannot be checked at all.',
             'The write must always happen before the lease check.'],
            'A check-then-act gap is another race. Validate atomically at the authority the write uses.'),
        multi('Which statements are correct? Select all that apply.',
              [('Wall clocks can drift or jump under adjustment.', True),
               ('A smaller Lamport timestamp does not prove causation.', True),
               ('Same-epoch retries still need idempotency checks.', True),
               ('Fencing tokens protect a provider that ignores them.', False)],
              'Fencing works only where the destination enforces it.'),
    ],
    'sd-29': [
        mcq('Does eventual convergence mean no user update was lost?',
            'No. A winner rule can converge after discarding an update.',
            ['Yes. Converged replicas always contain every user update.',
             'Yes, provided the regions\' clocks are kept synchronized.',
             'No. Converged replicas still disagree until a user reads.'],
            'Last-writer-wins selects a winner rather than preserving every intent.'),
        mcq('Can a CRDT counter alone guarantee never selling more than ten seats?',
            'No. Independent increments can overshoot; coordinate instead.',
            ['Yes. CRDTs enforce business constraints each time they merge.',
             'Yes, as long as every region uses its own grow-only counter.',
             'No. CRDT counters cannot count past ten in the first place.'],
            'Convergence does not preserve arbitrary business constraints. Coordination or a proven allocation scheme is needed.'),
        mcq('Region A\'s grow-only counter is {A:3, B:0} and region B\'s is {A:0, B:2}. After a component-wise max merge, what is the total?',
            '5', ['3', '2', '10'],
            'Merging gives {A:3, B:2}. Repeating the merge changes nothing.'),
        mcq('Two regions accept concurrent edits to a display name under last-writer-wins. What happens?',
            'One user\'s edit is discarded, though the replicas converge.',
            ['Both edits are merged into a single combined display name.',
             'The replicas never converge and keep both names forever.',
             'Both users see an error and must submit their edit again.'],
            'A documented winner rule or visible conflict resolution may be acceptable for display names.'),
        mcq('During a regional partition, how should a final-seat reservation behave?',
            'Route it to one fenced authority; the cut-off side waits.',
            ['Let both sides confirm the seat and reconcile it later.',
             'Use last-writer-wins on the seat record across regions.',
             'Keep a grow-only counter of seats sold in each region.'],
            'The isolated side offers a pending or unavailable result. Do not let both partitioned sides independently confirm the same seat.'),
    ],
    'sd-30': [
        mcq('Does a watermark make it impossible for older events to arrive later?',
            'No. It is a progress assumption; late data still needs a policy.',
            ['Yes. Events behind the watermark are rejected at the source.',
             'Yes, once a checkpoint has been taken after the watermark.',
             'No. Watermarks only apply to processing time, not event time.'],
            'Watermarks help decide when to emit windows; they are not proof.'),
        mcq('Does restoring a checkpoint undo an email already sent by a sink?',
            'No. External effects need their own idempotent or compensating path.',
            ['Yes. Restoring a checkpoint rolls back every effect it made.',
             'Yes, provided the sink that sent the email is replayable.',
             'No. Checkpoints store only the job configuration, never any of its state.'],
            'Checkpoints preserve processing state and source positions, not the outside world.'),
        mcq('Events with event times 10:01 and 10:04 arrive at processing time 10:06. Which window do they belong to?',
            'The [10:00, 10:05) event-time window.',
            ['The [10:05, 10:10) processing window.', 'Whichever window is open at 10:06.',
             'Neither; late events are dropped.'],
            'If that window was already emitted, the policy may update it, send corrections, or route late data elsewhere.'),
        mcq('What is the trade-off of waiting longer for late events?',
            'More complete results that arrive later and need more state.',
            ['Faster results that need less state held in memory.',
             'Nothing is lost, because waiting longer costs nothing at all.',
             'Duplicate events disappear without any extra work.'],
            'Aggressive watermarks give faster results while excluding or correcting more late data.'),
        multi('Which statements about stream processing are correct? Select all that apply.',
              [('Event time is when the event actually occurred.', True),
               ('Processing time is when the processor handles it.', True),
               ('An idle input can stall watermark progress.', True),
               ('Checkpoints alone give end-to-end exactly-once.', False)],
              'End-to-end exactly-once also needs replayable input and a compatible transactional or idempotent output.'),
    ],
}

CASE_STUDIES = {
    'cs-01': [
        mcq('Can two users both see a seat as available without violating correctness?',
            'Yes. The display may be stale; only one claim can succeed.',
            ['No. Seat maps must always be exactly current for everyone.',
             'No. If both see it, the seat has already been double-booked.',
             'Yes, but only if both users are viewing from the same cache.'],
            'Availability displays may lag; the authoritative claim and confirmation must still have one winner.'),
        mcq('Why not hold a database transaction open for the whole payment?',
            'It would hold locks through a slow call it cannot roll back.',
            ['Payment providers reject any call made inside a transaction.',
             'Database transactions cannot contain any read statements.',
             'Payments would become faster, but noticeably less secure.'],
            'A slow external call would retain locks and resources, and the transaction still could not roll back the provider\'s '
            'effect. Payment runs outside the short claim transaction.'),
        mcq('A late successful payment arrives after the seat was reassigned. What happens?',
            'Reconcile, then void or refund it; never issue a second ticket.',
            ['Issue a second ticket for the same seat to the paying buyer.',
             'Take the seat back from the new buyer and hand it to buyer A.',
             'Ignore the payment, since the hold had already expired.'],
            'A\'s delayed success must not overwrite B\'s ownership. An explicit workflow voids or refunds it.'),
        mcq('The opening burst is 50,000 reservation attempts a minute. About how many per second is that?',
            'About 833', ['About 50', 'About 3,000', 'About 83'],
            'Average per-seat traffic is misleading: many users can contend for the same best seat.'),
        mcq('Where must the one-confirmed-booking-per-seat rule be enforced?',
            'In the database, with a unique constraint or conditional update.',
            ['In the seat-map cache, which every reservation request reads.',
             'In application code only, checked before the insert runs.',
             'In the payment provider, which refuses a duplicate charge.'],
            'Never rely on a cache expiry as the sole reservation authority.'),
    ],
    'cs-02': [
        mcq('Does a balanced journal prove the provider and the application agree?',
            'No. Entries can balance yet be missing, duplicated or misclassified.',
            ['Yes. Balanced entries mean the two sets of books are correct by definition.',
             'Yes, provided that every journal entry records its currency.',
             'No. A journal cannot balance when a provider is involved.'],
            'Reconciliation is a primary path, not an emergency script.'),
        mcq('Can webhook arrival order be used as the authoritative payment sequence?',
            'No. Webhooks can repeat or reorder; reconcile canonical state.',
            ['Yes. Payment providers always send webhooks in event order.',
             'Yes, as long as each webhook carries a valid signature.',
             'No. Webhooks arrive in reverse order, so read them backwards.'],
            'A webhook may arrive before the API response or after a later status event. Validate transitions against canonical state.'),
        mcq('Why does a refund need its own operation identity?',
            'A refund is its own external effect that can also be uncertain.',
            ['Providers reject refunds that share the charge\'s customer ID.',
             'A new identity lets the original charge record be deleted.',
             'Refunds are only allowed on charges that have no identity.'],
            'A refund can be retried or end in an unknown state. If it times out, it is its own uncertain operation rather than a local revert.'),
        mcq('The provider accepts a charge but the response is lost, and the client retries. What should the service do?',
            'Keep the original operation ID and query or retry under it.',
            ['Create a new operation key and submit a fresh charge instead.',
             'Mark the payment as failed, since no response came back.',
             'Refund the charge immediately, just to be on the safe side.'],
            'Follow the provider\'s documented idempotency contract. If its window has passed, do not blindly submit a new charge; move the case to reconciliation.'),
        mcq('An internal transfer of 2,500 minor units is posted. What does the journal transaction contain?',
            '+2,500 and −2,500 in one transaction, same currency and reference.',
            ['A single +2,500 entry, recorded on the receiving account only.',
             'Two separate transactions, one for each of the two accounts.',
             'One floating-point entry of 25.00 in the major currency unit.'],
            'The sum is zero. A uniqueness rule stops duplicate events from posting it again.'),
    ],
    'cs-03': [
        mcq('Can lease expiry guarantee that only one worker is running a job?',
            'No. An old worker may be paused or cut off and resume later.',
            ['Yes. An expired worker stops automatically at its deadline.',
             'Yes, as long as each worker sends heartbeats while it runs.',
             'No. Leases only ever apply to the scheduler, not workers.'],
            'A heartbeat reduces needless replacement but cannot prove old work stopped.'),
        mcq('What should identify one occurrence of a recurring job?',
            'The schedule\'s stable ID plus a precisely defined occurrence.',
            ['The ID of whichever scheduler instance found the occurrence.',
             'The operating-system process ID of the worker running it.',
             'The wall-clock time at which the worker started running it.'],
            'A scheduled occurrence has one identity, independent of which scheduler finds it, even when several notice it.'),
        mcq('Does fencing a result row deduplicate every external effect?',
            'No. Each destination needs its own idempotency or authority check.',
            ['Yes. The fence on the result covers every side effect of the job.',
             'Yes, as long as emails are sent after the result is written.',
             'No. Fencing only works when the pool has exactly one worker.'],
            'An email provider that ignores the epoch is not protected by fencing the local result.'),
        mcq('One million runs a day with a 10× peak and a two-second mean execution time. Roughly how many runs are active at peak?',
            'About 232', ['About 23', 'About 2,000', 'About 116'],
            'Peak is about 116 runs/s; × 2 s ≈ 232 in flight, before safety margin.'),
        mcq('A user cancels a running job. Does the cancellation request prove the job stopped?',
            'No. It is a request; the job stops at its next safe point.',
            ['Yes. A cancellation request kills the worker process at once.',
             'Yes, as soon as the cancel API call has returned 200 OK.',
             'No. Running jobs can never be cancelled once they start.'],
            'Cancellation is a durable request. Completed effects may need compensation. A queued run may move straight to canceled; a running one may not.'),
    ],
    'cs-04': [
        mcq('Does a source-database commit mean the document is immediately searchable?',
            'No. Ingestion and index refresh add their own visibility delay.',
            ['Yes. The search index reads the source database directly.',
             'Yes, as long as the indexing process is keeping up fast enough.',
             'No. Documents only become searchable after a full rebuild.'],
            'Search is a rebuildable projection with an explicit freshness contract.'),
        mcq('Why keep version information on deletes?',
            'So a delayed update cannot resurrect a newer deletion.',
            ['Deletes run faster when they carry a version number.',
             'The search index requires a version on every request.',
             'It lets administrators undo deletions from the admin UI.'],
            'Deletes carry durable versioned tombstones or an equivalent replay-safe policy, so neither a delayed update nor a snapshot replay brings a document back.'),
        mcq('Can autocomplete share the exact access policy of public search by assumption?',
            'No. Suggestions can leak private titles and need their own rules.',
            ['Yes. Both of the features read from exactly the same indexed documents.',
             'Yes, as long as the suggestion results are cached per user.',
             'No. Autocomplete must never use any indexed titles at all.'],
            'Suggestions can reveal private titles or sensitive queries. Do not include private titles in a public prefix index.'),
        mcq('You rebuild the index while 20 updates/s continue. What prevents missing edits?',
            'Snapshot at a stream position, replay later changes, verify, switch.',
            ['Take a snapshot of the source and switch reads over to it immediately.',
             'Pause every write for the whole duration of the rebuild.',
             'Rebuild quickly and skip verification to shorten the gap.'],
            'A snapshot without a catch-up boundary can miss edits made during the rebuild. Switch the read alias only after verification.'),
        mcq('Access to a private resource is revoked while the index lags. Where is access enforced?',
            'At query or result delivery, through the authorization check.',
            ['Nowhere, until the search index catches up with the revoke.',
             'Only in the indexer, when it next processes the document.',
             'In the client\'s cache, which drops the result on refresh.'],
            'Eventual text freshness cannot justify a privacy leak.'),
    ],
    'cs-05': [
        mcq('Will raising a rollout threshold keep the old cohort if the rollout salt also changes?',
            'Not generally. A new salt reshuffles every user\'s bucket.',
            ['Yes. Raising a threshold only ever adds users to the cohort.',
             'Yes, as long as the flag key itself stays exactly the same.',
             'No. Thresholds can only be lowered once a rollout starts.'],
            'Keep the bucketing function, subject identity, encoding and salt fixed.'),
        mcq('Can a local flag cache guarantee an immediate kill switch during a partition?',
            'No. A bounded guarantee needs expiry and a stated failure policy.',
            ['Yes. Pushed updates reach every process instantly, even in a partition.',
             'Yes, provided the local cache refreshes itself every second.',
             'No. Kill switches only work when flags are read from disk.'],
            'A partitioned process cannot receive push updates. A bounded guarantee needs expiry or an online protocol.'),
        mcq('Does enabling a feature flag grant permission to use its API?',
            'No. Authorization has to enforce access on its own.',
            ['Yes. Turning the flag on is the permission itself.',
             'Yes, but only for the company\'s own internal users.',
             'No. Flags only control styling, never any behavior.'],
            'A flag enabling a user interface does not authorize the backend action.'),
        mcq('A rollout grows from 10% to 20%. How does the original 10% stay included?',
            'Keep the hash inputs and salt fixed; only raise the threshold.',
            ['Pick a new salt so the larger cohort is evenly distributed.',
             'Store every user\'s bucket in a browser cookie for later.',
             'Re-randomize every user\'s bucket once a day at midnight.'],
            'The old buckets remain a subset. Publish cross-language test vectors so every SDK agrees.'),
        mcq('A new service instance starts while the configuration endpoint is down. What should it evaluate?',
            'A valid persisted snapshot within policy, else the safe default.',
            ['Its own best guess at what the current configuration probably is.',
             'Nothing; block every request until the endpoint comes back.',
             'Every flag as enabled, so that no feature goes missing.'],
            'Use a persisted bootstrap snapshot under the staleness policy, or else the typed safe default. It must not invent the current configuration.'),
    ],
    'cs-06': [
        mcq('Does changing DNS establish a single writer?',
            'No. Old connections and cut-off servers can keep writing.',
            ['Yes. DNS decides where every write goes from then on.',
             'Yes, once the old DNS record\'s TTL has fully expired.',
             'No. DNS changes only redirect reads, never any writes.'],
            'A routing change alone cannot stop an isolated old server from committing. Authority must be enforced at the write boundary.'),
        mcq('Can the same RPO be assumed for every data class?',
            'No. Replication and recovery rules can differ by data class.',
            ['Yes. RPO is a fixed property of the region, not the data.',
             'Yes, as long as all of the data lives in the same database.',
             'No. RPO applies only to billing data, never to user data.'],
            'The scenario accepts a minute of lost progress but requires acknowledged billing records to survive.'),
        mcq('Is a globally reachable directory enough to make a service region-independent?',
            'No. Its own quorum and dependencies must survive the failures too.',
            ['Yes. The directory routes traffic around any failed region.',
             'Yes, as long as the directory itself is replicated to another region.',
             'No. A directory can only ever serve one region at a time.'],
            'Its data dependencies, identity services, keys and recovery paths count too. Shared global dependencies can defeat regional independence.'),
        mcq('A region serving 4,000 requests/s fails and its traffic splits equally across the other two. How much extra capacity does each need?',
            '2,000 requests/s', ['4,000 requests/s', 'About 1,333 requests/s', 'None at all'],
            'Plus the dependencies and warming that routed workload needs.'),
        mcq('What must happen before Region B accepts writes for Region A\'s tenants?',
            'A new authority epoch is installed and the old writer is fenced.',
            ['DNS is updated so that tenant traffic points at Region B.',
             'The asynchronous replica in Region B is promoted immediately.',
             'Region A is asked to stop, and B starts once A replies.'],
            'Install the epoch through a surviving coordination path and fence the old writer at every protected write authority. '
            'If the old authority cannot be excluded, invariant-sensitive writes stay unavailable.'),
    ],
}

QUESTIONS = {**BEGINNER, **INTERMEDIATE, **ADVANCED, **PRODUCTION, **EXPERT, **CASE_STUDIES}
