"""Quiz banks for the curriculum lessons and case studies, keyed by catalogue ID.

The catalogue's knowledge checks are short-answer, so each bank rewrites
them as MCQ or multi-select questions with plausible wrong answers, then adds
questions on the worked example, practice task and failure modes. Every
answer is taken from the lesson text in docs/learning. sd-01's bank lives
with its hand-adapted notes in learn/curriculum.py.

Choices are listed right answer first; the quiz shuffles them.
"""


def mcq(prompt, right, wrong, explanation):
    return {'prompt': prompt, 'choices': [(right, True)] + [(w, False) for w in wrong], 'explanation': explanation}


def multi(prompt, choices, explanation):
    return {'kind': 'multi', 'prompt': prompt, 'choices': choices, 'explanation': explanation}


BEGINNER = {
    'sd-02': [
        mcq('A client repeats DELETE /tasks/9. The first call returns 204 and the second returns 404. Is DELETE still idempotent?',
            'Yes. Idempotence concerns the intended effect on state, not identical status codes.',
            ['No. An idempotent operation must return the same status code every time.',
             'No. Only GET requests can be idempotent.'],
            'After either call the task is gone. The second response differs, but repeating the request did not change state further.'),
        mcq('POST /exports returns 202 Accepted. What does that tell the caller?',
            'The export was accepted for processing; completion needs a separate observation, such as an operation status URL.',
            ['The export file exists and can be downloaded now.',
             'The server created the export resource, exactly as 201 would.',
             'The request failed validation and should be retried.'],
            '202 means accepted, not completed. An asynchronous contract needs durable operation state the caller can read.'),
        multi('Which statements about HTTP method semantics are correct? Select all that apply.',
              [('GET is safe: the client does not request a state-changing action.', True),
               ('PUT and DELETE are idempotent in their intended effect.', True),
               ('POST is idempotent whenever the payload is identical.', False),
               ('A safe method must return an identical response every time.', False)],
              'Safety and idempotence describe what the client asks the server to change. POST has no general idempotency guarantee.'),
        mcq('Two clients read a task title at ETag v7. Client 1 writes with If-Match: v7 and creates v8. Client 2 then writes with If-Match: v7. What should happen?',
            'The server rejects client 2 with 412 Precondition Failed, and client 2 refreshes or resolves its edit.',
            ['The server applies client 2 because its write arrived last.',
             'The server merges both titles automatically.',
             'The server returns 202 and queues client 2 for later.'],
            'If-Match makes the write conditional on the version the client read. A stale precondition is detected instead of silently overwriting v8.'),
        mcq('Why is it unsafe to retry POST /payments automatically?',
            'POST has no general idempotency guarantee, so a retry can create a second payment unless the API defines deduplication, such as a stable request key.',
            ['HTTP clients are not allowed to resend POST requests.',
             'A retried POST always fails with 412 Precondition Failed.',
             'POST responses cannot be read after a timeout.'],
            'Automatic retries of POST are unsafe without an explicit deduplication contract.'),
    ],
    'sd-03': [
        mcq('A stable service handles 50 requests/s with a 0.2 s mean response time. Using Little\'s Law, how many requests are in flight on average?',
            '10', ['250', '0.004', '2.5'],
            'L = lambda × W = 50 × 0.2 = 10, provided throughput and latency are measured at the same boundary.'),
        multi('CPU sits at 20% but requests are timing out. What could explain it? Select all that apply.',
              [('Requests are waiting on locks.', True),
               ('Requests are waiting for database connections.', True),
               ('Requests are queued behind slow network responses.', True),
               ('Low CPU proves the service has spare capacity for every request.', False)],
              'Requests can wait on locks, connections, network responses or queues without consuming CPU.'),
        mcq('Throughput stays at 200 requests/s while mean response time rises from 0.15 s to 0.6 s. What happens to average in-flight work?',
            'It rises from 30 to 120 requests.',
            ['It stays at 30 because throughput did not change.', 'It falls to 7.5 requests.', 'It doubles to 60 requests.'],
            'In-flight work is throughput × time in system. The extra work can hold memory and sockets even while CPU stays low.'),
        mcq('990 requests take 20 ms and 10 take 2,000 ms. The mean is 39.8 ms. What does the mean hide?',
            'Ten severe delays that a tail percentile would expose.',
            ['Nothing: the mean is the right summary of user experience.',
             'That throughput fell during the measurement.',
             'That the service dropped the slow requests.'],
            'Tail percentiles describe slow requests. A mean can hide a small but painful slow population.'),
        mcq('Starting empty, a worker group receives 120 jobs/s and completes 100/s for five minutes. Arrivals then fall to 80/s. How long does the backlog take to drain?',
            'About 300 seconds.', ['About 75 seconds.', 'About 60 seconds.', 'It never drains.'],
            'The backlog grows by 20 × 300 = 6,000 jobs. Spare capacity is 100 − 80 = 20 jobs/s, so draining takes 300 s, assuming fixed capacity and no retries.'),
    ],
    'sd-04': [
        mcq('Does adding await make a CPU-heavy loop run in parallel?',
            'No. It lets the task suspend at awaitable operations; CPU parallelism needs an execution model that supports it.',
            ['Yes. Each await runs the next iteration on another core.',
             'Yes, as long as the loop runs inside a task group.'],
            'async syntax lets a task yield. It does not make CPU work parallel.'),
        mcq('When is a process-local mutex insufficient to protect an inventory rule?',
            'When other processes, servers or services can update the same inventory without taking that mutex.',
            ['Only when the mutex is held for more than a second.',
             'Never: a mutex always serializes every update.',
             'Only when the database has no transactions.'],
            'A process-local lock coordinates only that process. The shared authority has to enforce the rule.'),
        mcq('Two workers both read remaining_seats = 1, both see a seat, and both write 0 and issue a ticket. Which fix enforces the rule at the shared boundary?',
            'A conditional update that decrements only if remaining_seats > 0, checks that exactly one row changed, and creates the reservation in the same transaction.',
            ['A lock held inside each web server process.',
             'Re-reading remaining_seats until both workers agree.',
             'Writing remaining_seats twice to be sure.'],
            'The database can enforce the check and the change atomically. The group of related writes commits together or not at all.'),
        mcq('Two increments both read balance = 10 and both write 11. What happened?',
            'A lost update: two increments produced one net increase. An atomic balance = balance + 1 lets the database serialize them.',
            ['Nothing: 11 is the correct final value.',
             'A deadlock that the database resolved correctly.',
             'The second write was rolled back automatically.'],
            'Read-then-write interleavings lose updates. Push the increment into one atomic statement at the shared store.'),
        multi('Which statements about concurrency are correct? Select all that apply.',
              [('Concurrency means tasks are in progress during overlapping periods; parallelism means work runs simultaneously.', True),
               ('Calling a blocking function directly inside an event loop can stop it serving other tasks.', True),
               ('Cancelling a coroutine proves any remote effect it started was rolled back.', False),
               ('Optimistic version checks never need retries.', False)],
              'A cancelled coroutine may already have triggered an external effect. Optimistic checks work well when conflicts are rare but must retry when they occur.'),
    ],
    'sd-05': [
        mcq('Why might a sequential scan be the right plan?',
            'If the query needs much of the table, reading it sequentially can cost less than many index-guided table reads.',
            ['Sequential scans are always faster than index scans.',
             'The planner only scans sequentially when a table has no indexes.',
             'EXPLAIN cannot display index scans.'],
            'An index scan is not always better. Low-selectivity queries can favor scanning the table.'),
        mcq('Is EXPLAIN ANALYZE a read-only inspection for any SQL statement?',
            'No. It executes the statement, so writes and side-effecting functions really run.',
            ['Yes. It only estimates costs.',
             'Yes. PostgreSQL always rolls it back automatically.'],
            'EXPLAIN shows the planned strategy; EXPLAIN ANALYZE executes and measures. Use a disposable environment for statements with effects.'),
        mcq('A query filters tenant_id = 7 and status = \'open\', sorts by created_at and id descending, and returns 20 rows. Which index is the lesson\'s candidate?',
            '(tenant_id, status, created_at, id)',
            ['(created_at, id, tenant_id, status)', '(status)', '(id, tenant_id)'],
            'It groups the equality filters before the ordered range, with id breaking timestamp ties. Compare plans on representative data before trusting it.'),
        mcq('A dashboard loads 50 projects, then runs one query per project to fetch its owner. What is the main problem?',
            'An N+1 pattern: 51 queries. Fetch owners with a join or one bounded query keyed by owner IDs.',
            ['A missing index on the projects table.',
             'A sequential scan on the owners table.',
             'The page should be cached for a day.'],
            'An index may speed up each lookup while leaving the avoidable round trips in place.'),
        multi('What can an extra index cost? Select all that apply.',
              [('Extra work on every write that changes indexed data.', True),
               ('Storage space.', True),
               ('Maintenance effort.', True),
               ('Slower reads for every query on the table.', False)],
              'Every extra index adds write, storage and maintenance costs. It does not slow down unrelated reads.'),
    ],
    'sd-06': [
        mcq('Is "one million registered users" enough for a capacity estimate?',
            'No. You need activity, actions per active user, timing, payload sizes and retention.',
            ['Yes. Divide it by 86,400 to get requests per second.',
             'Yes, once you add 20% headroom.'],
            'Registered users say nothing about how often people act, how large requests are, or when they arrive.'),
        mcq('A flash crowd appears. Which assumption changes first?',
            'The peak arrival pattern and concurrency; the registered-user count may not change at all.',
            ['The registered-user count.', 'The data retention period.', 'The average payload size.'],
            'Daily averages conceal bursts. Estimate steady and peak demand separately.'),
        mcq('100,000 daily active learners each load 20 lessons a day. What is the average read rate?',
            'About 23 reads/s.', ['About 2,000 reads/s.', 'About 231 reads/s.', 'About 0.23 reads/s.'],
            '2 million reads a day ÷ 86,400 s ≈ 23.15 reads/s. A 20× peak would be about 463 reads/s.'),
        mcq('Which of these is an invariant rather than a performance objective?',
            'Never confirm two owners for one seat.',
            ['99% of accepted reads finish within 300 ms.',
             '99.9% of requests succeed over 30 days.',
             'p95 search latency stays under 250 ms.'],
            'An invariant must always hold. An objective states a target over a measurement window.'),
        mcq('100,000 users each submit five 500-byte events a day, kept for 365 days. How much raw event storage is that?',
            '91.25 GB', ['7.5 GB', '250 MB', '912.5 GB'],
            '250 MB a day × 365 = 91.25 GB in decimal units, before indexes, replicas and backups.'),
        mcq('Before choosing the number of application servers, what should you measure?',
            'The throughput one server sustains at the required latency and error objectives, and the downstream database and cache demand of a realistic request mix.',
            ['The number of registered users.',
             'The vendor\'s advertised requests per server.',
             'Average daily traffic only.'],
            'Include failure headroom rather than dividing by an untested requests-per-server guess.'),
    ],
}

INTERMEDIATE = {
    'sd-07': [
        mcq('Should a database slowdown always fail application liveness?',
            'No. Restarting healthy application processes can make a shared dependency incident worse.',
            ['Yes. Liveness should mirror the health of every dependency.',
             'Yes, so the load balancer stops sending traffic.'],
            'A liveness probe that fails whenever the database is slow can restart every application server during a database incident.'),
        mcq('Does an equal connection count across instances mean equal request load?',
            'No. Connections differ in how many requests they carry, how long they last and what they cost.',
            ['Yes. Each connection carries one request.',
             'Yes, whenever round robin is used.'],
            'A long-lived connection carrying many requests makes connection counts a poor proxy for load.'),
        mcq('Four instances each sustain 100 requests/s at the target latency, and traffic is 240/s. Two instances fail. What happens?',
            'The two survivors each see 120/s, above their measured operating point.',
            ['Each survivor sees 60/s, which is fine.', 'Each survivor sees 80/s.', 'Total traffic falls to 120/s.'],
            'With one instance gone each sees 80/s; with two gone, 120/s. The arithmetic assumes balanced requests of similar cost.'),
        multi('Which statements about Kubernetes probes are correct? Select all that apply.',
              [('Readiness decides whether a pod receives Service traffic.', True),
               ('A failing liveness probe can trigger a container restart.', True),
               ('Startup checks protect slow initialization.', True),
               ('A failing readiness probe deletes the pod.', False)],
              'Readiness withdraws a pod from traffic; liveness restarts containers; startup probes protect slow starts.'),
        mcq('An instance is being shut down. What should happen first?',
            'Withdraw readiness and allow for routing propagation while the server keeps serving.',
            ['Kill the process; clients will retry.',
             'Close every open connection immediately.',
             'Fail liveness so the pod is restarted.'],
            'Then stop admitting new work, let short requests drain within a bounded grace period, and force termination only at the declared deadline.'),
    ],
    'sd-08': [
        mcq('Does a 30-second TTL alone guarantee that every served value is at most 30 seconds behind the authority?',
            'No. Delayed fills, stale upstream reads and refresh behavior can make the data older than the entry\'s lifetime.',
            ['Yes. The TTL bounds staleness exactly.',
             'Yes, as long as the cache is in memory.'],
            'TTL limits a copy\'s lifetime. It is not a complete consistency protocol.'),
        mcq('What does HTTP Cache-Control: no-cache mean?',
            'A stored response must be validated before reuse. It is not the same as no-store.',
            ['Caches must never store the response.',
             'The response is deleted after zero seconds.',
             'Only a CDN may store the response.'],
            'no-store forbids storage by caches subject to the directive; no-cache allows storage but requires validation.'),
        mcq('At 1,000 reads/s and a 95% hit rate, the origin serves about 50 reads/s. A restart empties the cache. What happens?',
            'Origin demand can rise toward 1,000 reads/s until the cache refills.',
            ['Origin demand stays at 50 reads/s.', 'Origin demand drops to zero.', 'Origin demand rises to 1,050 reads/s.'],
            'A cache outage needs a controlled fallback; sending every miss to an already saturated database is not a recovery plan.'),
        mcq('Reader A misses and reads version 4. Writer B commits version 5 and invalidates the key. Reader A then fills the cache with version 4. What went wrong?',
            'A stale-fill race: the invalidation happened before A\'s fill, so version-aware fills or a coherence protocol are needed.',
            ['The TTL was too short.',
             'The eviction policy removed version 5.',
             'Nothing: invalidation guarantees freshness.'],
            'Invalidation happened, yet stale data returned. Version-aware fills prevent an older version replacing a newer one.'),
        mcq('A product page may show stock up to 30 seconds old, but checkout must never sell unavailable stock. Where should the checkout decision be made?',
            'At the authoritative store, with a conditional update; the product page can read from the cache.',
            ['From the cached stock count with a 30-second TTL.',
             'From the CDN copy of the product page.',
             'In the browser, from the last page load.'],
            'Cache the display with an explicit freshness policy, and enforce the inventory invariant where the data is authoritative.'),
        multi('What belongs in a shared cache key for a multi-tenant API? Select all that apply.',
              [('The tenant.', True),
               ('Authorization-relevant scope.', True),
               ('Representation variants, where they apply.', True),
               ('The time of the request.', False)],
              'Never let a shared cached answer bypass an access check.'),
    ],
    'sd-09': [
        mcq('A request fails with a pool acquisition timeout. Does that prove the database query ran slowly?',
            'No. The request may never have obtained a connection or submitted a query.',
            ['Yes. The timeout measures query time.',
             'Yes, because pools only time out during queries.'],
            'Waiting for a connection and executing a query are different stages.'),
        mcq('Why include deployment overlap in a connection budget?',
            'Old and new instances can run together, multiplying potential connections before the old fleet drains.',
            ['Deployments reset every pool to zero connections.',
             'Databases double their connection limit during deploys.',
             'Rollouts close all idle connections.'],
            'If a deployment temporarily doubles instances, potential demand can double with it.'),
        mcq('12 application instances each run 2 worker processes with a pool of 10. What is the maximum connection budget?',
            '240', ['120', '24', '480'],
            '12 × 2 × 10 = 240, which already exceeds a database allowing 200 connections, before background jobs or rollout overlap.'),
        mcq('Latency rose from 80 ms to 800 ms. Queries still take about 50 ms, but pool acquisition takes 700 ms. Why might doubling the pool size fail?',
            'If the database has no spare capacity, more connections move the queue into the database and add contention.',
            ['A larger pool always lowers latency.',
             'Pools cannot be resized at runtime.',
             'It would cut query time to 5 ms.'],
            'Check transaction durations and leaks, aggregate connection budgets, and database saturation or lock waits first.'),
        mcq('What is a risk of PgBouncer transaction pooling?',
            'Code that assumes session-local settings persist can break, because the server connection is released after each transaction.',
            ['It reserves one server connection for each client session.',
             'It disables transactions entirely.',
             'It blocks prepared statements in every configuration.'],
            'Session pooling reserves a server connection per client session. Prepared-statement support depends on the feature and configuration.'),
    ],
    'sd-10': [
        mcq('Does a publisher confirm mean the report has been generated?',
            'No. It concerns the broker accepting the publication, not a consumer generating the report.',
            ['Yes. The broker confirms after the consumer finishes.',
             'Yes, if the queue is durable.'],
            'Publisher confirms and consumer acknowledgements cover different stages; one does not imply the other.'),
        mcq('Why is oldest-job age a useful queue metric?',
            'It shows how long accepted work has waited, while a count ignores job cost and arrival patterns.',
            ['It is cheaper to compute than queue length.',
             'It measures worker CPU usage.',
             'It replaces the error rate.'],
            'Ten expensive jobs may be worse than a thousand cheap ones.'),
        mcq('A worker commits the business effect, then crashes before acknowledging the message. What happens next?',
            'The message can be redelivered, so the repeat must recognize the existing result.',
            ['The work is lost.',
             'The broker sees the commit and drops the message.',
             'The producer is asked to publish a new job.'],
            'Acknowledging after the effect can allow duplicates; acknowledging before it can lose work after a crash.'),
        mcq('Ten workers each process one job per second while 1,200 jobs/min arrive for ten minutes. How large is the backlog afterwards?',
            '6,000 jobs', ['12,000 jobs', '600 jobs', 'No backlog'],
            'Capacity is 600 jobs/min, so the queue grows by 600 jobs a minute for ten minutes.'),
        mcq('You then run 15 workers and arrivals return to 600/min. How long does the 6,000-job backlog take to drain?',
            '20 minutes', ['10 minutes', '40 minutes', 'About 7 minutes'],
            '15 workers complete 900 jobs/min, leaving 300/min spare: 6,000 ÷ 300 = 20 minutes.'),
        multi('How should a job queue handle a job with malformed input? Select all that apply.',
              [('Cap the number of attempts.', True),
               ('Classify errors as retryable or not.', True),
               ('Move it to a visible dead-letter or failed-job path.', True),
               ('Retry it forever with exponential backoff.', False)],
              'Retrying malformed input wastes capacity. Failures need a visible path.'),
    ],
    'sd-11': [
        mcq('Does a strongly consistent object store guarantee fresh CDN responses?',
            'No. The CDN can keep serving a previously fetched copy under its own cache policy.',
            ['Yes. Object writes invalidate every CDN copy.',
             'Yes, as long as uploads use PUT.'],
            'Read-after-write consistency in the object store does not refresh a downstream CDN.'),
        mcq('Why keep an upload record in a pending state?',
            'It separates byte transfer from validation and publication, so incomplete workflows can be recovered.',
            ['To hide the file from its owner.',
             'Object stores refuse uploads without one.',
             'To lower storage costs.'],
            'If the upload succeeds but the metadata update fails, the user still sees pending and a reconciler can finish or retire it.'),
        mcq('A teacher replaces a worksheet at the same URL and some students still see the old one. Which publish flow gives predictable version identity?',
            'Upload a new immutable key, validate it, then atomically switch the metadata to reference it.',
            ['Overwrite the object in place.',
             'Switch the metadata pointer first, then upload.',
             'Use an unguessable key and email the new link.'],
            'Immutable, versioned keys make replacement explicit; old cached URLs keep identifying the old bytes.'),
        mcq('What happens if the metadata pointer switches before the new object is ready?',
            'Readers can receive missing or invalid content.',
            ['Nothing: the CDN waits for the object.',
             'The old object is served automatically.',
             'The upload is cancelled.'],
            'Publication has to follow object readiness.'),
        multi('Which statements about direct-to-storage uploads are correct? Select all that apply.',
              [('They reduce application bandwidth.', True),
               ('The upload capability should be short-lived and narrowly scoped.', True),
               ('The object needs validation after upload.', True),
               ('An obscure object key is enough access control for private content.', False)],
              'An obscure key is not permission. Private content needs access control at delivery time.'),
    ],
    'sd-12': [
        mcq('Why is created_at alone often an insufficient cursor key?',
            'Several rows can share a timestamp, so a unique tiebreaker is needed to continue without ambiguity.',
            ['Timestamps cannot be sorted.',
             'created_at changes whenever a row is read.',
             'Cursors must use primary keys only.'],
            'Sort by (created_at, id) and continue after the last tuple.'),
        mcq('Does keyset pagination guarantee an immutable result set?',
            'No. It defines continuation; concurrent updates, deletions and snapshot policy still decide what is visible.',
            ['Yes. The cursor freezes the collection.',
             'Yes, once the cursor is signed.'],
            'A stable cursor does not freeze membership. Snapshot semantics need a separate design.'),
        mcq('Page one returned the 10:03 and 10:02 items. A 10:04 item arrives. What does OFFSET 2 return first on page two?',
            'The 10:02 item again.', ['The 10:01 item.', 'The 10:04 item.', 'An error.'],
            'The new item shifts every offset by one, repeating an item. A cursor after the unique (10:02, id) pair continues with older entries.'),
        mcq('Why can large OFFSET values be expensive?',
            'The skipped rows still have to be computed.',
            ['OFFSET disables every index.', 'OFFSET locks the table.', 'The database sends all skipped rows to the client.'],
            'Keyset pagination avoids this but usually cannot jump straight to page 10,000.'),
        multi('What should the server check when it receives a pagination cursor? Select all that apply.',
              [('That it matches the same tenant, filters and sort contract.', True),
               ('Authorization, on every page.', True),
               ('Tampering, through a signature or server-side cursor state, when that matters.', True),
               ('Nothing: an opaque encoding makes it trustworthy.', False)],
              'Treat a cursor as untrusted input. Opaque encoding alone provides neither authorization nor tamper protection.'),
    ],
    'sd-31': [
        mcq('Does consistent hashing stop a single hot key from overloading its node?',
            'No. Every request for that key still goes to the node that owns it; spreading its load needs a workload change, such as caching or sub-keys.',
            ['Yes. Virtual nodes spread one key over several servers.',
             'Yes, once the cluster is rebalanced.'],
            'Partitioning spreads distinct keys; it cannot split one. Cache the key\'s reads or split its writes across suffixed sub-keys.'),
        mcq('Why do virtual nodes help when a node fails?',
            'Each node holds many small arcs, so the failed node\'s keys scatter across many survivors instead of landing on one neighbor.',
            ['They keep a full copy of every key on every node.',
             'They stop any key from moving when a node fails.',
             'They let the failed node keep serving its keys.'],
            'With one ring position per node, a failed node\'s whole load falls on its single clockwise neighbor.'),
        mcq('A cache holds 1,000,000 keys on four nodes placed by hash(key) mod N. A fifth node joins. About how many keys change node?',
            'About 800,000', ['About 200,000', 'About 250,000', 'None'],
            'A key stays only when its hash leaves the same remainder mod 4 and mod 5, which happens for 4 of every 20 hash values. '
            'For a cache, the moved keys become near-simultaneous misses.'),
        mcq('The same cluster uses a consistent-hash ring with many virtual nodes per server. When the fifth node joins, which keys move?',
            'About 200,000, the new node\'s fair share, drawn from all four old nodes.',
            ['About 800,000, reshuffled among all five nodes.',
             'About 250,000, all taken from one neighbor.',
             'None until their cache entries expire.'],
            'A joining node takes over only the keys on the arcs it lands on. No key moves between two nodes that both stayed.'),
        mcq('A range-partitioned table is keyed by event timestamp. Why does its write throughput stop scaling?',
            'Every new row lands in the last range, so one partition takes all the inserts and no split point divides that load.',
            ['Range partitions cannot store timestamps.',
             'Timestamps all hash to the same value.',
             'Range scans lock the whole table.'],
            'Lead the key with a high-cardinality field such as a user ID, or hash-shard it and accept that ordered reads must merge shards.'),
        multi('Which statements about hash partitioning are correct? Select all that apply.',
              [('It spreads sequential keys evenly across partitions.', True),
               ('An ordered scan over the key must ask every partition and merge the results.', True),
               ('It keeps neighboring keys together, so a prefix scan touches one partition.', False),
               ('With hash(key) mod N, adding a node moves only the new node\'s fair share of keys.', False)],
              'Hashing trades sort order for an even spread. Placement by hash mod N ties each key to the node count, so most keys move when N changes.'),
    ],
}

ADVANCED = {
    'sd-13': [
        mcq('Three nested layers each make up to three attempts. How many calls can reach the deepest dependency?',
            '27', ['9', '3', '6'],
            '3 × 3 × 3 = 27. One retry owner or a propagated retry budget prevents the multiplication.'),
        mcq('A payment request times out. May the client treat the payment as failed?',
            'No. It may have committed; inspect durable state or reconcile using the original operation identity.',
            ['Yes. A timeout means the server never processed it.',
             'Yes, after one retry with a new operation key.'],
            'A timeout is the caller deciding it has waited long enough, not a message that nothing happened.'),
        mcq('A request has a 1,000 ms deadline. Attempt one took 300 ms, backoff waited 100 ms, attempt two took 400 ms. Should the client start a third 400 ms attempt?',
            'No. Only 200 ms remain for more work and for returning a response.',
            ['Yes. The per-attempt timeout of 400 ms allows it.',
             'Yes. Jitter extends the deadline.'],
            'Bound retries by the total deadline as well as per-attempt limits.'),
        mcq('What does jitter add to exponential backoff?',
            'It spreads clients across different retry times so they do not retry in step after an outage.',
            ['It makes each retry faster.', 'It caps the number of attempts.', 'It makes the operation idempotent.'],
            'Fixed retry intervals synchronize clients after an outage.'),
        multi('Which belong in a retry policy? Select all that apply.',
              [('A total deadline.', True),
               ('A cap on attempts.', True),
               ('Retrying only errors and operations whose contract permits it.', True),
               ('Retrying every error immediately to keep latency low.', False)],
              'Every retry adds work exactly when a dependency may be struggling. Idempotency protects repeated effects, not load.'),
    ],
    'sd-14': [
        mcq('Is a content hash always a valid substitute for a client operation key?',
            'No. Two intentionally separate operations can have identical payloads.',
            ['Yes. Identical content always means a retry.',
             'Yes, if the hash is SHA-256.'],
            'Hashing content alone can merge two intentional identical purchases.'),
        mcq('Why must idempotency-key retention be documented?',
            'Duplicate suppression only covers the period and scope for which identifying state exists; a later duplicate may be treated as new.',
            ['Keys are kept forever, so it only matters for audits.',
             'Retention sets the request timeout.',
             'It is a compliance formality with no effect on behavior.'],
            'Choose retention from the retry and replay horizon, then communicate it.'),
        mcq('A caller reuses an idempotency key with a different amount. What should the service do?',
            'Reject the conflicting reuse after comparing the stored request fingerprint.',
            ['Silently replay the original result.',
             'Process it as a new operation.',
             'Overwrite the original operation.'],
            'A reused key with changed input should not silently replay the wrong result.'),
        mcq('Transaction T claims key (tenant7, award, abc), awards a credit, records the result and commits, but its response is lost. Duplicate U arrives. What happens?',
            'U cannot claim the key because of the unique constraint, so it returns T\'s committed result.',
            ['U awards a second credit.',
             'U waits until T\'s response is delivered.',
             'U deletes T\'s key and starts over.'],
            'This works because the key record and the effect share one transaction. An email sent inside T would not become transactional.'),
        mcq('A worker crashes after a remote provider succeeded but before recording it locally. What should recovery do?',
            'Query the provider, or repeat with the same provider operation key under its deduplication contract, before recording the result.',
            ['Mark the operation failed and retry with a new key.',
             'Mark it succeeded, since a pending row implies success.',
             'Delete the pending row so the client can try again.'],
            'A local pending row cannot prove whether the remote effect happened.'),
    ],
    'sd-15': [
        mcq('Does transactional Kafka processing automatically make an external SQL update exactly once?',
            'No. The external effect needs its own coordinated or idempotent commit strategy.',
            ['Yes. Kafka transactions cover every downstream system.',
             'Yes, if consumers read committed records only.'],
            'Kafka transactions can combine output records and consumed offsets; they do not commit an unrelated database.'),
        mcq('Can messages delivered in order produce effects out of order?',
            'Yes. Concurrent workers, retries and different execution times can change completion order.',
            ['No. Delivery order always equals effect order.',
             'Only when the broker loses messages.'],
            'Include entity versions or sequence numbers and define what consumers do with gaps or stale updates.'),
        mcq('A consumer increments a SQL counter for event e42, then crashes before committing its broker offset. Which design keeps replay from counting e42 twice?',
            'Record e42 in a unique processed-events table in the same SQL transaction as the increment.',
            ['Commit the broker offset before the increment.',
             'Retry the increment faster.',
             'Use one global ordering for all events.'],
            'Committing the offset first only changes the failure into a missing increment.'),
        mcq('Version 12 of a search document arrives before version 11. When is rejecting version 11 safe?',
            'When each event carries the complete versioned state of the document.',
            ['Always: older versions are never needed.',
             'Never: every event must be applied in arrival order.',
             'When the events are deltas such as "increment quantity by one".'],
            'Discarding an earlier delta can lose a required change. The payload semantics decide the rule.'),
        multi('Which statements about delivery guarantees are correct? Select all that apply.',
              [('At-least-once processing can repeat work so recovery can continue.', True),
               ('At-most-once processing can lose work.', True),
               ('Ordering is typically scoped to a partition or stream.', True),
               ('Exactly-once is a broker property that covers every downstream effect.', False)],
              'Exactly-once is meaningful only inside a defined protocol boundary.'),
    ],
    'sd-16': [
        mcq('Does the outbox pattern remove duplicate event delivery?',
            'No. It closes the local dual-write gap; a relay can still republish after an uncertain outcome.',
            ['Yes. Each outbox row is published exactly once.',
             'Yes, when change data capture is used.'],
            'Consumers must handle duplicates, helped by an event ID.'),
        mcq('Why store a schema version on each event?',
            'Consumers need a stable way to interpret payloads as producers evolve independently.',
            ['Brokers reject events without one.', 'It orders events across partitions.', 'It encrypts the payload.'],
            'Explicit domain events give a more stable contract than raw table changes.'),
        mcq('What does the outbox pattern make atomic?',
            'The business state change and the intent to publish, written in one local transaction.',
            ['Publishing and consuming the event.',
             'The broker acknowledgement and the database commit.',
             'The event and the email it triggers.'],
            'A relay later publishes committed events by polling or change data capture.'),
        mcq('The broker is down for an hour. What happens to orders confirmed in that hour?',
            'Their events wait in the outbox and are published once a relay works again, provided they are retained.',
            ['Their events are lost.',
             'The order transactions roll back.',
             'The events are published twice as a precaution.'],
            'The database still holds the publication intent.'),
        mcq('Why is deleting every outbox row older than one hour unsafe?',
            'Age does not prove publication; retention has to follow relay progress and replay guarantees.',
            ['It is safe: relays publish within seconds.',
             'Deleting rows locks the orders table.',
             'Rows older than an hour are needed only for audits.'],
            'A relay may be offline for hours. Monitor lag against retained data.'),
    ],
    'sd-17': [
        mcq('Does compensation restore every outside observer to the original state?',
            'No. Effects such as notifications, fees and observations can be irreversible.',
            ['Yes. Compensation erases the original action.',
             'Yes, when the saga is orchestrated.'],
            'Compensation is a new business action: a refund differs from pretending no charge happened.'),
        mcq('Why persist the saga coordinator\'s state?',
            'A restarted coordinator must resume or repair the workflow without forgetting completed steps or issuing contradictory actions.',
            ['For analytics only.', 'Queues require it.', 'It makes each step faster.'],
            'Durable state, idempotent commands and explicit recovery paths are necessary.'),
        mcq('An order is payment_pending when the provider call times out. What should the saga do?',
            'Reconcile the provider operation using its stable identity; do not treat the timeout as a decline.',
            ['Mark the payment declined.',
             'Release the inventory and charge again.',
             'Confirm the booking optimistically.'],
            'A timeout leaves the outcome unknown.'),
        mcq('Payment succeeds late, after the inventory hold expired and the item went to someone else. What next?',
            'Re-reserve if that is explicitly allowed; otherwise void or refund. Never confirm unavailable inventory.',
            ['Confirm the order anyway.',
             'Ignore the late payment.',
             'Delete the payment record.'],
            'Record compensation progress until it succeeds or enters manual repair.'),
        multi('Which statements about sagas are correct? Select all that apply.',
              [('Orchestration has a coordinator that tracks steps and commands participants.', True),
               ('Choreography lets services react to events without a central controller.', True),
               ('Compensation is a new business action, not an erasure of history.', True),
               ('A saga usually isolates each workflow from the others.', False)],
              'A saga usually does not provide isolation: another workflow may see reserved inventory before final confirmation.'),
    ],
    'sd-18': [
        mcq('Can a requests-per-second limit alone protect a dependency whose latency suddenly rises tenfold?',
            'Not reliably. In-flight work can grow dramatically, so concurrency and waiting also need bounds.',
            ['Yes. A rate limit bounds all resource use.',
             'Yes, if the limit is per tenant.'],
            'A service can have a low request rate but high concurrency when calls become slow.'),
        mcq('Why can a fallback make an outage worse?',
            'The alternative path may be more expensive or have less capacity than the normal one.',
            ['Fallbacks always return errors.',
             'Fallbacks disable load shedding.',
             'Fallbacks are only used by clients.'],
            'Switching every cache miss to SQL can amplify an incident. Fallbacks need their own budget.'),
        mcq('Arrivals reach 1,400 jobs/s while workers sustain 1,000/s. How long does a 2,000-job buffer take to fill from empty?',
            'About 5 seconds.', ['About 2 seconds.', 'About 1.4 seconds.', 'It never fills.'],
            'The deficit is 400/s: 2,000 ÷ 400 = 5 s. A bigger buffer only postpones the failure.'),
        mcq('Jobs expire after three seconds. Why is a very deep queue a problem?',
            'Workers spend capacity on jobs whose results nobody can use any more.',
            ['Deep queues are always faster to drain.',
             'Expired jobs are retried automatically.',
             'Queue depth has no effect on latency.'],
            'Admission and prioritization should reflect the usefulness deadline.'),
        mcq('One noisy tenant uses all the capacity under a single global limit. What gives more control?',
            'Per-tenant budgets with a shared ceiling.',
            ['A larger global queue.', 'Retrying rejected requests immediately.', 'Removing the global limit.'],
            'Poor prioritization can also starve low-priority tenants, so budgets need a documented policy.'),
        multi('Which pairings of control and what it bounds are correct? Select all that apply.',
              [('A rate limit bounds arrivals over time.', True),
               ('A concurrency limit bounds in-flight work.', True),
               ('A queue limit bounds waiting work.', True),
               ('A rate limit bounds the memory held by slow requests.', False)],
              'These controls address different resources.'),
    ],
}

PRODUCTION = {
    'sd-19': [
        mcq('For a 99.5% target over 200,000 eligible events, how many bad events are allowed?',
            '1,000', ['995', '10,000', '100'],
            '200,000 × (1 − 0.995) = 1,000.'),
        mcq('Is an error budget permission to ignore every error below the threshold?',
            'No. It is a decision tool; severe correctness, security or concentrated user failures may need action anyway.',
            ['Yes. Any error inside the budget is acceptable.',
             'Yes, until the window resets.'],
            'SLOs should guide decisions such as slowing releases or repairing a dependency.'),
        mcq('An SLO requires 99.9% of eligible requests to be good over 30 days. An interval has a 1% bad fraction. What is the burn rate?',
            '10', ['1', '0.1', '100'],
            'Burn rate = observed bad fraction ÷ allowed bad fraction = 0.01 ÷ 0.001.'),
        mcq('If that burn rate persists and traffic is uniform, roughly how soon is a fresh 30-day budget consumed?',
            'About 3 days.', ['About 10 days.', 'About 30 days.', 'About 3 hours.'],
            '30 days ÷ 10 = 3 days. With variable traffic, the event counts decide consumption.'),
        mcq('A dashboard endpoint returns HTTP 200 quickly but leaves out the learner\'s saved progress in 2% of responses. How should the indicator count those?',
            'As bad events, because they violate the response contract.',
            ['As good events, because the status is 200.',
             'As good events, because they are fast.',
             'Not at all: they are client-side problems.'],
            'A status-code-only indicator misses this failure. Define success to include the required data.'),
    ],
    'sd-20': [
        mcq('Why should request IDs usually not be metric labels?',
            'Their nearly unbounded values multiply time series and storage cost; logs and traces suit individual IDs.',
            ['Metrics cannot store strings.',
             'Request IDs are secret.',
             'Labels are limited to numbers.'],
            'Prefer bounded labels such as route templates and outcome classes.'),
        mcq('Does a fast acceptance endpoint prove a background workflow is fast?',
            'No. Queue waiting and execution can dominate end-to-end latency after acceptance.',
            ['Yes. Acceptance latency is end-to-end latency.',
             'Yes, if the endpoint returns 202.'],
            'Track acceptance latency, queue age, processing latency and end-to-end completion separately.'),
        mcq('An export\'s acceptance span takes 70 ms, it waits 85 s in the queue, and the worker takes 4.93 s. What reveals the user\'s 90-second wait?',
            'End-to-end completion latency together with queue age.',
            ['The web server latency chart.', 'Worker CPU usage.', 'Broker throughput.'],
            'The web server chart looks healthy while the user waits.'),
        mcq('Queue age is rising while workers sit idle. What does that suggest first?',
            'A scheduling or consumption problem, rather than provider throttling.',
            ['Provider throttling.', 'Too many workers.', 'A fast acceptance endpoint.'],
            'Active attempts receiving throttle responses would point toward provider limits instead. Validate either hypothesis with worker and dependency signals.'),
        multi('Which statements about telemetry signals are correct? Select all that apply.',
              [('Metrics summarize measurements.', True),
               ('Logs record events.', True),
               ('Traces connect timed operations across a request.', True),
               ('A trace ID replaces a durable business operation ID across retries and days of processing.', False)],
              'Trace relationships express execution structure; durable business IDs identify an operation across retries and reconciliation.'),
    ],
    'sd-21': [
        mcq('Why can a constant-virtual-user test hide overload?',
            'As responses slow down, each virtual user sends fewer requests, so the offered arrival rate falls.',
            ['Virtual users ignore errors.',
             'Constant-user tests cannot measure latency.',
             'The load generator crashes first.'],
            'This is coordinated omission: the test eases off exactly when the service struggles.'),
        multi('What must accompany a throughput result? Select all that apply.',
              [('Workload assumptions.', True),
               ('The offered load.', True),
               ('Latency and error outcomes.', True),
               ('The number of virtual users, on its own.', False)],
              'Report the environment and relevant resource or dependency limits too.'),
        mcq('100 virtual users each repeat a request as soon as it finishes. Response time rises from 100 ms to 1 s. What happens to the offered load?',
            'It falls from about 1,000 requests/s to about 100 requests/s.',
            ['It stays at about 1,000 requests/s.',
             'It rises to about 10,000 requests/s.',
             'It falls to zero.'],
            'The slowdown reduced test pressure tenfold. An arrival-rate test preserves the intended demand.'),
        mcq('Which kind of test exposes leaks and slow growth?',
            'A soak test.', ['A stress test.', 'A recovery test.', 'A smoke test.'],
            'Stress tests find limits; soak tests expose growth, leaks and maintenance effects; recovery tests measure the return to health.'),
        mcq('In an open workload model, how is new work scheduled?',
            'Independently of when earlier work completes.',
            ['Only after each iteration finishes.',
             'Only when the service is idle.',
             'At a rate set by the service\'s response time.'],
            'Neither model is universally correct; pick the one that matches the real workload.'),
    ],
    'sd-22': [
        mcq('Does deploying the previous application image reverse a database migration?',
            'No. Data and schema changes persist independently and may no longer be compatible.',
            ['Yes. The image carries the old schema.',
             'Yes, if the migration ran in a transaction.'],
            'Prefer a forward repair when a rollback would misread newer data.'),
        mcq('Why validate a backfill before dropping the old field?',
            'Missing, stale or wrongly transformed values could otherwise become permanent, user-visible data loss.',
            ['Dropping a column requires a validated backfill.',
             'Validation speeds up the drop.',
             'Backfills cannot run after a drop.'],
            'Verify counts and semantics before contracting.'),
        mcq('You are replacing full_name with display_name using expand, migrate, contract. What comes first?',
            'Add the new nullable display_name column while the old code still works.',
            ['Drop full_name.', 'Switch reads to display_name.', 'Backfill display_name.'],
            'Then write both, backfill in batches, verify, switch reads, and remove the old column only when nothing needs it.'),
        mcq('Why run a backfill in small, restartable batches?',
            'It competes with normal queries and replication, so it should be throttled while lag and locks are watched.',
            ['Large batches are rejected by PostgreSQL.',
             'Small batches skip validation.',
             'Batches make the backfill reversible.'],
            'Avoid overwriting a newer display_name while backfilling.'),
        mcq('An event field changes from a string amount to integer minor units. What must happen before producers emit the new form?',
            'Consumers are upgraded to understand both forms.',
            ['The string field is dropped.',
             'Historical events are deleted.',
             'Consumers are paused until producers switch.'],
            'Version the event contract and keep historical replay working.'),
    ],
    'sd-23': [
        mcq('Does an unguessable UUID authorize access to a record?',
            'No. It makes guessing harder but is not a permission check.',
            ['Yes. Only the owner can know it.',
             'Yes, over HTTPS.'],
            'Check access whenever client-supplied identifiers select records.'),
        mcq('Is enabling row-level security enough when the application connects as a superuser?',
            'No. Superusers bypass row security; the role and policy configuration are part of the guarantee.',
            ['Yes. Row-level security applies to every role.',
             'Yes, once the policies are written.'],
            'Superusers, BYPASSRLS roles and normally table owners bypass policies.'),
        mcq('Tenant A and tenant B each have a report numbered 17. What is wrong with the cache key report:17?',
            'It is ambiguous: one tenant can receive the other tenant\'s cached report.',
            ['Nothing, if the SQL query filters by tenant.',
             'Cache keys cannot contain numbers.',
             'It will never be hit.'],
            'Scope the key to the authorized tenant and representation, and recheck required permissions.'),
        mcq('A queued export job takes tenant_id from the request body. What is the risk?',
            'A caller can choose another tenant\'s data.',
            ['None, because the job runs in the background.',
             'The job runs twice.',
             'The export is slower.'],
            'The job must carry a trusted tenant identity and the right authorization policy.'),
        multi('Which statements are correct? Select all that apply.',
              [('Authentication answers who is making the request.', True),
               ('Authorization answers whether this identity may perform this action on this resource now.', True),
               ('Tests run only as a table owner or superuser can hide row-policy mistakes.', True),
               ('A valid login is enough to read any record in the tenant\'s database.', False)],
              'Use application roles representative of production when testing.'),
    ],
    'sd-24': [
        mcq('Why is a current replica not a substitute for historical backups?',
            'It may faithfully replicate destructive or corrupting changes.',
            ['Replicas cannot be read during an outage.',
             'Replicas are always behind.',
             'Replicas use a different storage format.'],
            'A backup preserves a recoverable past; a replica copies the present.'),
        mcq('What makes a recovery time objective (RTO) credible?',
            'A timed, representative recovery exercise covering data restoration, validation, dependencies and traffic restoration.',
            ['A successful nightly backup job.',
             'The time it takes to start a new machine.',
             'The vendor\'s published restore speed.'],
            'A successful backup job alone is not proof of recoverability.'),
        mcq('Corruption began at 14:02. The latest base backup is from 02:00 and archived logs run to 14:05. Where should the restore stop?',
            'At a consistent point just before the damaging transaction.',
            ['At 14:05, the latest point available.',
             'At 02:00, the base backup.',
             'At 14:05, then delete the corrupt rows by hand.'],
            'Restoring to the latest point would replay the corruption. Every required log must exist.'),
        mcq('The restore takes 45 minutes and verification plus routing another 20. Starting the machine took 2. What is the observed recovery time at least?',
            '65 minutes', ['2 minutes', '45 minutes', '20 minutes'],
            'Measure each phase; the recovery time is not the machine start time.'),
        multi('Which statements are correct? Select all that apply.',
              [('RPO is the tolerated data loss, expressed in time.', True),
               ('RTO is the tolerated restoration duration.', True),
               ('A backup in the same failure or credential domain may disappear with the original.', True),
               ('A logical dump can replace a physical base backup for write-ahead-log replay.', False)],
              'Point-in-time recovery combines a base backup with a continuous sequence of write-ahead logs.'),
    ],
}

EXPERT = {
    'sd-25': [
        mcq('Does serializability alone require a later transaction to see every earlier completed transaction in wall-clock order?',
            'No. That real-time requirement belongs to strict serializability.',
            ['Yes. Serializability always follows real time.',
             'Yes, for read-only transactions.'],
            'Serializability means equivalent to some serial order, not necessarily the real-time one.'),
        mcq('Under linearizability, can a stale read be legal when it overlaps a write?',
            'Yes. It may be ordered before the overlapping write.',
            ['No. Every read must see the latest write.',
             'Only if the clocks are synchronized.'],
            'Operations that complete before another starts impose stronger constraints.'),
        mcq('A register holds 0. A writes 1 and gets success at t2. B starts a read at t3, after t2, and gets 0. No other write happened. Is this history linearizable?',
            'No. B\'s read began after A\'s write completed, so it must return 1 or later.',
            ['Yes. Replicas may lag.',
             'Yes, if B\'s clock is behind A\'s.'],
            'Write down invocation and completion intervals rather than sorting by client timestamps.'),
        mcq('Two doctors each read that both are on call, then each sets their own on_call flag to false. Why don\'t per-key atomic writes prevent this?',
            'The invariant spans two keys, and both reads happen before either write.',
            ['Atomic writes are not durable.',
             'The writes conflict on the same key.',
             'The database lost one write.'],
            'Protect the shared predicate with a suitable isolation or locking strategy, or route the decision through one authoritative roster object.'),
        multi('Which statements are correct? Select all that apply.',
              [('Read-your-writes is a session guarantee, not global linearizability.', True),
               ('Eventual convergence does not specify a finite freshness bound.', True),
               ('During a partition, linearizable operations cannot stay available on every separated side.', True),
               ('R + W > N on its own proves a protocol linearizable.', False)],
              'Quorum arithmetic alone is not a proof: write ordering, version selection and failure behavior matter.'),
    ],
    'sd-26': [
        mcq('Does a timeout prove the leader is dead?',
            'No. It may be slow or partitioned; elections and term rules must keep safety despite false suspicions.',
            ['Yes. Leaders always answer within the timeout.',
             'Yes, if two followers agree.'],
            'Failure detectors can be wrong. The protocol tolerates that.'),
        mcq('Why must membership changes be coordinated?',
            'Independent old and new majorities can otherwise make conflicting decisions without intersecting.',
            ['New members cannot read the log otherwise.',
             'Coordination speeds up elections.',
             'Leaders refuse unknown members.'],
            'Replacing {A,B,C} with {C,D,E} by hand lets {A,B} and {D,E} each act as a majority.'),
        mcq('Five voting members split 3–2. Which side can commit new entries?',
            'The three-member side, if it has an eligible leader.',
            ['Both sides, independently.', 'Neither side.', 'The two-member side, if it holds the old leader.'],
            'Five voters need three votes. The minority cannot commit on its own.'),
        mcq('A three-voter cluster has one failed member. Why is adding an empty node as a fourth voter risky?',
            'The majority rises from two to three; with one voter down and the new one not caught up, progress can stop.',
            ['Four voters cannot elect a leader.',
             'The new voter becomes leader immediately.',
             'It forces a full restart.'],
            'Keep the working quorum, use the supported learner or replacement workflow, and wait for catch-up.'),
        mcq('What is a learner in Raft-based systems?',
            'A non-voting member that catches up before promotion.',
            ['A candidate that has lost an election.',
             'A follower that votes but never leads.',
             'A replica that accepts writes locally.'],
            'Learners avoid increasing the voting quorum prematurely.'),
    ],
    'sd-27': [
        mcq('Can a prepared participant safely abort just because its timer expired?',
            'No. A commit decision may already exist, so it must follow the protocol\'s recovery rules.',
            ['Yes. Timeouts always mean abort.',
             'Yes, if it has not heard from other participants.'],
            'A prepared participant promised not to choose an outcome independently.'),
        mcq('Does consensus automatically turn arbitrary database writes into a distributed transaction?',
            'No. Consensus orders agreed state; atomic commitment and isolation need additional protocol design.',
            ['Yes. Replicated logs are transactions.',
             'Yes, with a majority quorum.'],
            'Atomicity across participants and isolation are separate problems.'),
        mcq('The coordinator durably records commit, tells store A, and crashes before telling store B. What must B do?',
            'Stay prepared, recover the durable commit decision, and then commit.',
            ['Abort once its wait timer expires.',
             'Commit on its own initiative.',
             'Ask A to roll back.'],
            'A has already committed. B cannot abort just because it waited.'),
        mcq('What does a participant promise when it votes "prepared" in two-phase commit?',
            'It has durably recorded enough state to finish later and will not choose an outcome independently.',
            ['It has already committed.',
             'It will abort if the coordinator is slow.',
             'It has released its locks.'],
            'Prepared transactions keep their locks, which can block ordinary work.'),
        multi('You need to move credits between two balances. Which statements are correct? Select all that apply.',
              [('One local transaction can protect both balances if they live in one authority.', True),
               ('Two-phase commit can leave participants prepared, holding locks, while a participant is unreachable.', True),
               ('A saga can expose the debit before the credit.', True),
               ('Two-phase commit defines transaction isolation automatically.', False)],
              'Atomicity does not define isolation. Choose based on the invariant and availability needs.'),
    ],
    'sd-28': [
        mcq('Does a distributed lock physically stop an expired worker?',
            'No. The worker may carry on; the protected resource must reject stale authority.',
            ['Yes. Lease expiry kills the process.',
             'Yes, if heartbeats stop.'],
            'A paused process can wake up later and act on an old belief.'),
        mcq('Does a monotonic clock order events on different machines?',
            'No. Its guarantee concerns elapsed time within its own clock domain.',
            ['Yes. Monotonic clocks never go backwards anywhere.',
             'Yes, once synchronized by NTP.'],
            'Monotonic clocks measure local elapsed time; they do not establish a universal order.'),
        mcq('A worker holding epoch 41 stalls, its lease expires, and a worker with epoch 42 publishes. Worker 41 resumes and tries to publish. What should happen?',
            'The store atomically compares epochs and rejects the epoch-41 write.',
            ['The later write wins, so 41 overwrites 42.',
             'Both results are kept.',
             'Worker 41 is blocked by the lock service.'],
            'Checking only that a worker once held a lease lets the stale result overwrite the new one.'),
        mcq('Why is checking the lease in one call and then writing in a separate call unsafe?',
            'Ownership can change between the check and the write; validate atomically at the authority the write uses.',
            ['Two calls double the latency.',
             'Leases cannot be read.',
             'Writes must happen before checks.'],
            'A check-then-act gap is another race.'),
        multi('Which statements are correct? Select all that apply.',
              [('Wall clocks can drift or jump.', True),
               ('A smaller Lamport timestamp alone does not prove one event caused another.', True),
               ('Retries within the same epoch still need idempotency or version checks.', True),
               ('Fencing tokens protect an email provider that ignores them.', False)],
              'Fencing works only where the destination enforces it.'),
    ],
    'sd-29': [
        mcq('Does eventual convergence mean no user update was lost?',
            'No. A deterministic winner rule can converge after discarding a concurrent update.',
            ['Yes. Converged replicas contain every update.',
             'Yes, with synchronized clocks.'],
            'Last-writer-wins selects a winner rather than preserving every intent.'),
        mcq('Can a CRDT counter alone guarantee never selling more than ten seats?',
            'No. Independent increments can exceed the limit; coordination or a proven allocation scheme is needed.',
            ['Yes. CRDTs enforce business constraints.',
             'Yes, with a grow-only counter.'],
            'Convergence does not preserve arbitrary business constraints.'),
        mcq('Region A\'s grow-only counter is {A:3, B:0} and region B\'s is {A:0, B:2}. After a component-wise max merge, what is the total?',
            '5', ['3', '2', '10'],
            'Merging gives {A:3, B:2}. Repeating the merge changes nothing.'),
        mcq('Two regions accept concurrent edits to a display name under last-writer-wins. What happens?',
            'One user\'s edit is discarded, even though the replicas converge.',
            ['Both edits are merged.',
             'The replicas never converge.',
             'Both users see an error.'],
            'A documented winner rule or visible conflict resolution may be acceptable for display names.'),
        mcq('During a regional partition, how should a final-seat reservation behave?',
            'Route it to one fenced authority; the isolated side offers a pending or unavailable result.',
            ['Let both sides confirm and reconcile later.',
             'Use last-writer-wins on the seat.',
             'Use a grow-only counter per region.'],
            'Do not let both partitioned sides independently confirm the same seat.'),
    ],
    'sd-30': [
        mcq('Does a watermark make it impossible for older events to arrive later?',
            'No. It is the processor\'s progress assumption; the system still needs a late-data policy.',
            ['Yes. Late events are rejected at the source.',
             'Yes, once a checkpoint is taken.'],
            'Watermarks help decide when to emit windows; they are not proof.'),
        mcq('Does restoring a checkpoint undo an email already sent by a sink?',
            'No. External effects need their own transactional, idempotent or compensating treatment.',
            ['Yes. Checkpoints roll back all effects.',
             'Yes, if the sink is replayable.'],
            'Checkpoints preserve processing state and source positions, not the outside world.'),
        mcq('Events with event times 10:01 and 10:04 arrive at processing time 10:06. Which window do they belong to?',
            'The [10:00, 10:05) event-time window.',
            ['The [10:05, 10:10) window.', 'Whichever window is open when they are processed.', 'None: they are dropped.'],
            'If that window was already emitted, the policy may update it, send corrections, or route late data elsewhere.'),
        mcq('What is the trade-off of waiting longer for late events?',
            'Results are more complete but arrive later and need more retained state.',
            ['Results are faster and smaller.',
             'Nothing: waiting is free.',
             'Duplicates disappear.'],
            'Aggressive watermarks give faster results while excluding or correcting more late data.'),
        multi('Which statements about stream processing are correct? Select all that apply.',
              [('Event time is when the event occurred.', True),
               ('Processing time is when the processor handles the event.', True),
               ('An idle input can hold back watermark progress unless handled explicitly.', True),
               ('Checkpoints alone give exactly-once effects end to end.', False)],
              'End-to-end exactly-once also needs replayable input and a compatible transactional or idempotent output.'),
    ],
}

CASE_STUDIES = {
    'cs-01': [
        mcq('Can two users both see a seat as available without violating correctness?',
            'Yes. The display may be stale; the authoritative claim and confirmation must still have one winner.',
            ['No. Seat maps must always be exactly current.',
             'No. It means the seat was double-booked.'],
            'Availability displays may lag; confirmation checks authoritative ownership.'),
        mcq('Why not hold a database transaction open for the whole payment?',
            'A slow external call would hold locks and resources, and the transaction still could not roll back the provider\'s effect.',
            ['Payment providers reject calls made inside transactions.',
             'Transactions cannot contain reads.',
             'It would make payments faster but less secure.'],
            'Payment runs outside the short claim transaction.'),
        mcq('A late successful payment arrives after the seat was reassigned. What happens?',
            'Reconcile and void or refund under an explicit workflow; do not issue a second ticket.',
            ['Issue a second ticket for the same seat.',
             'Take the seat back from the new buyer.',
             'Ignore the payment.'],
            'A\'s delayed success must not overwrite B\'s ownership.'),
        mcq('The opening burst is 50,000 reservation attempts a minute. About how many per second is that?',
            'About 833', ['About 50', 'About 3,000', 'About 83'],
            'Average per-seat traffic is misleading: many users can contend for the same best seat.'),
        mcq('Where must the one-confirmed-booking-per-seat rule be enforced?',
            'In the database model, through a uniqueness constraint or conditional update.',
            ['In the seat-map cache.', 'In application code only.', 'In the payment provider.'],
            'Never rely on a cache expiry as the sole reservation authority.'),
    ],
    'cs-02': [
        mcq('Does a balanced journal prove the provider and the application agree?',
            'No. Entries can balance while being missing, duplicated under different identities, or assigned the wrong business meaning.',
            ['Yes. Balanced entries mean the books are correct.',
             'Yes, if every entry has a currency.'],
            'Reconciliation is a primary path, not an emergency script.'),
        mcq('Can webhook arrival order be used as the authoritative payment sequence?',
            'No. Delivery can repeat or reorder; validate transitions and reconcile canonical state.',
            ['Yes. Providers send webhooks in order.',
             'Yes, if the webhook is signed.'],
            'A webhook may arrive before the API response or after a later status event.'),
        mcq('Why does a refund need its own operation identity?',
            'It is a separate external effect that can also be retried or end in an uncertain state.',
            ['Refunds reuse the charge\'s key.',
             'Providers require a new customer ID.',
             'It lets the charge be deleted.'],
            'If a refund times out, it is its own uncertain operation rather than a local revert.'),
        mcq('The provider accepts a charge but the response is lost, and the client retries. What should the service do?',
            'Keep the original operation ID and query or retry under the provider\'s documented contract.',
            ['Create a new operation key and charge again.',
             'Mark the payment failed.',
             'Refund immediately to be safe.'],
            'If the provider\'s idempotency window has passed, do not blindly submit a new charge; move the case to reconciliation.'),
        mcq('An internal transfer of 2,500 minor units is posted. What does the journal transaction contain?',
            '+2,500 and −2,500 in the same transaction and currency, with the same operation reference.',
            ['A single +2,500 entry.',
             'Two separate transactions, one per account.',
             'A floating-point amount of 25.00.'],
            'The sum is zero. A uniqueness rule stops duplicate events from posting it again.'),
    ],
    'cs-03': [
        mcq('Can lease expiry guarantee that only one worker is running a job?',
            'No. An old worker may be paused or partitioned and resume later.',
            ['Yes. Expired workers stop automatically.',
             'Yes, with heartbeats.'],
            'A heartbeat reduces needless replacement but cannot prove old work stopped.'),
        mcq('What should identify one occurrence of a recurring job?',
            'A stable schedule identity plus a precisely defined occurrence, independent of which scheduler finds it.',
            ['The ID of the scheduler that found it.',
             'The worker\'s process ID.',
             'The time the worker started.'],
            'A scheduled occurrence has one identity even when several schedulers notice it.'),
        mcq('Does fencing a result row deduplicate every external effect?',
            'No. Every affected destination needs a compatible idempotency or authority protocol.',
            ['Yes. The fence covers all side effects.',
             'Yes, if emails are sent after the write.'],
            'An email provider that ignores the epoch is not protected by fencing the local result.'),
        mcq('One million runs a day with a 10× peak and a two-second mean execution time. Roughly how many runs are active at peak?',
            'About 232', ['About 23', 'About 2,000', 'About 116'],
            'Peak is about 116 runs/s; × 2 s ≈ 232 in flight, before safety margin.'),
        mcq('A user cancels a running job. Does the cancellation request prove the job stopped?',
            'No. It is a durable request; a running job notices it at a safe point, and completed effects may need compensation.',
            ['Yes. Cancellation kills the worker.',
             'Yes, once the API returns 200.'],
            'A queued run may move straight to canceled; a running one may not.'),
    ],
    'cs-04': [
        mcq('Does a source-database commit mean the document is immediately searchable?',
            'No. Ingestion and search refresh add separate visibility stages.',
            ['Yes. The index reads the database directly.',
             'Yes, if the indexer is fast.'],
            'Search is a rebuildable projection with an explicit freshness contract.'),
        mcq('Why keep version information on deletes?',
            'So a delayed update or snapshot replay cannot resurrect a document deleted by a newer version.',
            ['Deletes are faster with versions.',
             'The index requires versions on every call.',
             'To support undo in the admin UI.'],
            'Deletes carry durable versioned tombstones or an equivalent replay-safe policy.'),
        mcq('Can autocomplete share the exact access policy of public search by assumption?',
            'No. Suggestions can reveal private titles or sensitive queries and need their own visibility controls.',
            ['Yes. Both read the same data.',
             'Yes, if results are cached.'],
            'Do not include private titles in a public prefix index.'),
        mcq('You rebuild the index while 20 updates/s continue. What prevents missing edits?',
            'Snapshot at a known change-stream position, apply later versioned changes, verify, then switch the read alias.',
            ['Take a snapshot and switch reads immediately.',
             'Pause all writes for the rebuild.',
             'Rebuild without verification to save time.'],
            'A snapshot without a catch-up boundary can miss edits made during the rebuild.'),
        mcq('Access to a private resource is revoked while the index lags. Where is access enforced?',
            'At query or result delivery, through the authorization boundary.',
            ['Nowhere until the index catches up.',
             'Only in the indexer.',
             'In the client\'s cache.'],
            'Eventual text freshness cannot justify a privacy leak.'),
    ],
    'cs-05': [
        mcq('Will raising a rollout threshold keep the old cohort if the rollout salt also changes?',
            'Not generally. Changing the hash input reshuffles the buckets.',
            ['Yes. Thresholds only ever add users.',
             'Yes, if the flag key stays the same.'],
            'Keep the bucketing function, subject identity, encoding and salt fixed.'),
        mcq('Can a local flag cache guarantee an immediate kill switch during a partition?',
            'No. A bounded guarantee needs expiry or an online protocol, plus a stated failure policy.',
            ['Yes. Push updates arrive instantly.',
             'Yes, if the cache is refreshed every second.'],
            'A partitioned process cannot receive push updates.'),
        mcq('Does enabling a feature flag grant permission to use its API?',
            'No. Authorization must enforce access independently.',
            ['Yes. The flag is the permission.',
             'Yes, for internal users.'],
            'A flag enabling a user interface does not authorize the backend action.'),
        mcq('A rollout grows from 10% to 20%. How does the original 10% stay included?',
            'Keep the hash inputs and salt fixed and raise only the threshold, so the old buckets remain a subset.',
            ['Pick a new salt for the larger cohort.',
             'Store every user\'s bucket in a cookie.',
             'Re-randomize daily.'],
            'Publish cross-language test vectors so every SDK agrees.'),
        mcq('A new service instance starts while the configuration endpoint is down. What should it evaluate?',
            'A valid persisted bootstrap snapshot under the staleness policy, or else the typed safe default.',
            ['Its best guess of the current configuration.',
             'Nothing: block every request until the endpoint returns.',
             'Every flag as enabled.'],
            'It must not invent the current configuration.'),
    ],
    'cs-06': [
        mcq('Does changing DNS establish a single writer?',
            'No. Existing connections and partitioned old servers can carry on; authority must be enforced at the write boundary.',
            ['Yes. DNS decides where writes go.',
             'Yes, once the TTL expires.'],
            'A routing change alone cannot stop an isolated old server from committing.'),
        mcq('Can the same RPO be assumed for every data class?',
            'No. Replication, acknowledgement, retention and recovery rules can differ by invariant and data class.',
            ['Yes. RPO is a property of the region.',
             'Yes, if all data shares one database.'],
            'The scenario accepts a minute of lost progress but requires acknowledged billing records to survive.'),
        mcq('Is a globally reachable directory enough to make a service region-independent?',
            'No. Its own quorum, data dependencies, identity services, keys and recovery paths must survive the required failures.',
            ['Yes. The directory routes around failed regions.',
             'Yes, if it is replicated.'],
            'Shared global dependencies can defeat regional independence.'),
        mcq('A region serving 4,000 requests/s fails and its traffic splits equally across the other two. How much extra capacity does each need?',
            '2,000 requests/s', ['4,000 requests/s', 'About 1,333 requests/s', 'None'],
            'Plus the dependencies and warming that routed workload needs.'),
        mcq('What must happen before Region B accepts writes for Region A\'s tenants?',
            'A new authority epoch is installed through a surviving coordination path, and the old writer is fenced at every protected write authority.',
            ['DNS is updated to point at Region B.',
             'The asynchronous replica is promoted immediately.',
             'Region A is asked to stop, and B starts once it replies.'],
            'If the old authority cannot be excluded, invariant-sensitive writes stay unavailable.'),
    ],
}

QUESTIONS = {**BEGINNER, **INTERMEDIATE, **ADVANCED, **PRODUCTION, **EXPERT, **CASE_STUDIES}
