# Generated by Django 5.2.16 on 2026-07-18 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🧩', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DesignChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('prompt', models.TextField(help_text='The scenario shown to the player, e.g. "Design a URL shortener".')),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_challenges', to='learn.concept')),
            ],
        ),
        migrations.CreateModel(
            name='DesignAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('xp_awarded', models.IntegerField(default=0)),
                ('is_perfect', models.BooleanField(default=False)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_attempts', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learn.designchallenge')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.CharField(default='Drag each definition onto the term it matches.', max_length=255)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_challenges', to='learn.concept')),
            ],
        ),
        migrations.CreateModel(
            name='MatchingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('xp_awarded', models.IntegerField(default=0)),
                ('is_perfect', models.BooleanField(default=False)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_attempts', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learn.matchingchallenge')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=150)),
                ('definition', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='learn.matchingchallenge')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderingChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.CharField(default='Drag the steps into the correct order.', max_length=255)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_challenges', to='learn.concept')),
            ],
        ),
        migrations.CreateModel(
            name='OrderingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('xp_awarded', models.IntegerField(default=0)),
                ('is_perfect', models.BooleanField(default=False)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_attempts', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learn.orderingchallenge')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('correct_position', models.PositiveIntegerField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='learn.orderingchallenge')),
            ],
            options={
                'ordering': ['correct_position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DesignChallengeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, help_text='Correct to place on the canvas.')),
                ('is_distractor', models.BooleanField(default=False, help_text='Wrong for this scenario — placing it costs points.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_components', to='learn.designchallenge')),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.componenttype')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('challenge', 'component_type')},
            },
        ),
        migrations.CreateModel(
            name='DesignChallengeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_connections', to='learn.designchallenge')),
                ('from_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learn.componenttype')),
                ('to_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learn.componenttype')),
            ],
            options={
                'unique_together': {('challenge', 'from_component', 'to_component')},
            },
        ),
    ]
