# Generated by Django 5.2.16 on 2026-07-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_componenttype_designchallenge_designattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unlock_all_content',
            field=models.BooleanField(default=False, help_text='Superuser-only preview toggle: bypasses chapter level-gating entirely.'),
        ),
    ]
