# Generated by Django 5.2.16 on 2026-07-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_userprofile_unlock_all_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='notes_sections',
            field=models.JSONField(blank=True, default=list, help_text="Structured notes, rendered behind the 'View Notes' toggle. List of {heading, body, deep_dive: {title, body} | null}. Also powers Study Mode (one flashcard per section)."),
        ),
        migrations.AlterField(
            model_name='concept',
            name='summary',
            field=models.TextField(help_text='Short one- or two-sentence teaser shown above the Notes toggle.'),
        ),
    ]
