# Generated by Django 5.2.16 on 2026-07-26 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_concept_notes_sections_alter_concept_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('prompt', models.TextField(help_text='Full problem statement shown to the learner: task, input/output format, example.')),
                ('constraints', models.TextField(blank=True)),
                ('starter_code', models.TextField(blank=True, help_text='Python 3 stub shown in the editor before the learner edits it.')),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('source_scenario', models.TextField(blank=True, help_text="The admin's original free-text scenario this was generated from, kept for audit/regeneration.")),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_challenges', to='learn.concept')),
            ],
            options={
                'ordering': ['difficulty', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CodingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0)),
                ('xp_awarded', models.IntegerField(default=0)),
                ('is_perfect', models.BooleanField(default=False)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_attempts', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learn.codingchallenge')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdin', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('is_sample', models.BooleanField(default=False, help_text='Sample cases are shown to the learner up front; non-samples stay hidden and only count toward grading.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='learn.codingchallenge')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
