# Generated by Django 5.2.16 on 2026-07-26 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_codingchallenge_codingattempt_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['topic__order', 'difficulty', 'order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='concept',
            options={'ordering': ['chapter__topic__order', 'chapter__difficulty', 'chapter__order', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1, help_text='Difficulty tier used to level content within a topic section.'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Cross-book section this chapter belongs to (drives dashboard grouping). `book` is kept only for provenance/attribution and the book_worm badge.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='learn.topic'),
        ),
    ]
