# Generated by Django 5.2.16 on 2026-07-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_topic_alter_chapter_options_alter_concept_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('mcq', 'Multiple choice (single answer)'), ('multi', 'Multiple choice (select all that apply)'), ('tf', 'True / False')], default='mcq', max_length=8),
        ),
    ]
