# Generated by Django 5.2.16 on 2026-09-27 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_alter_question_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlawChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('prompt', models.TextField(help_text='Scenario shown above the diagram, e.g. how many flaws are planted.')),
                ('canvas_width', models.PositiveIntegerField(default=1000, help_text='SVG viewBox width the part geometry is drawn in.')),
                ('canvas_height', models.PositiveIntegerField(default=430, help_text='SVG viewBox height the part geometry is drawn in.')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flaw_challenges', to='learn.concept')),
            ],
        ),
        migrations.CreateModel(
            name='FlawAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('xp_awarded', models.IntegerField(default=0)),
                ('is_perfect', models.BooleanField(default=False)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flaw_attempts', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learn.flawchallenge')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlawPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable id within the diagram, used by the page and seed data.', max_length=40)),
                ('kind', models.CharField(choices=[('node', 'Box'), ('edge', 'Arrow')], default='node', max_length=4)),
                ('label', models.CharField(help_text='Box title, or the spoken name of an arrow.', max_length=100)),
                ('sublabel', models.CharField(blank=True, help_text='Box: second line under the title. Arrow: caption drawn beside it (optional).', max_length=100)),
                ('geometry', models.JSONField(default=dict, help_text='Box: {"x", "y", "w", "h"}. Arrow: {"d": SVG path} plus {"lx", "ly"} if it has a caption.')),
                ('is_flaw', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True, help_text='Healthy parts: why this part is fine. Flawed parts show their correct reason instead.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='learn.flawchallenge')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('challenge', 'key')},
            },
        ),
        migrations.CreateModel(
            name='FlawReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='learn.flawpart')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
