# Generated by Django 5.2.16 on 2026-09-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_quorumchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='curriculum',
            field=models.JSONField(blank=True, default=dict, help_text='Curriculum lesson or case study metadata from docs/learning/catalogue.json: {id, type, stage, stage_title, minutes, objectives, prerequisites, sources, scope}. Empty for content outside the curriculum.'),
        ),
    ]
