# Generated by Django 5.2.16 on 2026-09-29 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0012_ringchallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Section this chapter belongs to across collections (drives dashboard grouping). `book` names the content collection and drives the collection-completion badge.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='learn.topic'),
        ),
        migrations.AlterField(
            model_name='designchallenge',
            name='prompt',
            field=models.TextField(help_text='The scenario shown to the player, e.g. "Build the ticket-booking flow".'),
        ),
        migrations.AlterField(
            model_name='quorumchallenge',
            name='source',
            field=models.CharField(blank=True, help_text='Curriculum lessons and primary sources this draws on.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ringchallenge',
            name='source',
            field=models.CharField(blank=True, help_text='Curriculum lessons and primary sources this draws on.', max_length=255),
        ),
    ]
