# Generated by Django 5.2.16 on 2026-09-29 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0013_help_text_updates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitBudgetChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('prompt', models.TextField(help_text='Scenario shown above the specs.')),
                ('source', models.CharField(blank=True, help_text='Curriculum lessons and primary sources this draws on.', max_length=255)),
                ('stages', models.JSONField(default=list, help_text='A list of build and clock stages. See learn/bitbudget.py.')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bit_budget_challenges', to='learn.concept')),
            ],
        ),
        migrations.CreateModel(
            name='BitBudgetAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('xp_awarded', models.IntegerField(default=0)),
                ('is_perfect', models.BooleanField(default=False)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bit_budget_attempts', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learn.bitbudgetchallenge')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
